package egovframework.ezMobile.ezEmail.service.impl;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.TimeZone;

import javax.annotation.Resource;
import javax.mail.Flags;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.UIDFolder;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import egovframework.com.cmm.EgovMessageSource;
import egovframework.ezEKP.ezCommon.service.EzCommonService;
import egovframework.ezEKP.ezEmail.logic.IMAPAccess;
import egovframework.ezEKP.ezEmail.util.EzEmailUtil;
import egovframework.ezMobile.ezEmail.service.MEmailService;
import egovframework.ezMobile.ezOption.vo.MCommonVO;
import egovframework.let.utl.fcc.service.CommonUtil;
import org.egovframe.rte.fdl.cmmn.EgovAbstractServiceImpl;

@Service("MEmailService")
public class MEmailServiceImpl extends EgovAbstractServiceImpl implements MEmailService {

	private static final Logger logger = LoggerFactory.getLogger(MEmailServiceImpl.class);
	
	@Autowired
	private CommonUtil commonUtil;
	
	@Resource(name = "EzCommonService")
    private EzCommonService ezCommonService;
	
	@Resource(name="egovMessageSource")
	private EgovMessageSource egovMessageSource;
	
	@Autowired
	private EzEmailUtil ezEmailUtil;
	
	@Autowired
	private Properties config;
	
	@Resource(name = "jspw")
    private String jspw;
	
	@SuppressWarnings("unchecked")
	@Override
	public JSONArray getMainMailList(MCommonVO info, Locale locale, String filter, String listSize) {
        
		IMAPAccess ia = null;
        JSONArray messageJsonArray = new JSONArray();
        
		try {

			String folderId = "INBOX";
			String start = "0";
			String end = (Integer.parseInt(start) + Integer.parseInt(listSize) - 1) + "";
	        String userId = info.getUserId();
	      
	        logger.debug("userID : " + userId+ ",folderId : " + folderId + ",listLength : " + listSize
	        		+"start : " + start+ ",end : " + end); 
	        
	        Message[] messages = null;
			
			
			String domainName = ezCommonService.getTenantConfig("DomainName", info.getTenantId());
			String userEmail = info.getUserId() + "@" + domainName;
			String password = jspw;
			
			ia = IMAPAccess.getInstance(config.getProperty("config.MailServerAddress"), config.getProperty("config.IMAPPort"),
					userEmail, password, egovMessageSource, locale, ezEmailUtil);
					
			Folder folder = ia.getFolder(folderId);		
			folder.open(Folder.READ_ONLY);
	        
	        boolean isUnreadOnly = false;
	        boolean isImportantOnly = false;
	        int startNo = 0;
			int endNo = 0;
	        
        	if (filter.equals("isUnreadOnly")) {
        		isUnreadOnly = true;
        	} else if (filter.equals("isImportantOnly")) {
        		isImportantOnly = true;
        	}
        	
        	startNo = Integer.parseInt(start);
			endNo = Integer.parseInt(end);
			int listCount = endNo - startNo + 1;
			
			if (listCount < 0) {
				listCount = 0;
			}
        	
    		messages = ezEmailUtil.searchFolder(ia, userEmail, folder, "", "", null, new Date(), false, 
    				isUnreadOnly, isImportantOnly, "receivedDate", false, startNo, listCount, true, null, info.getTenantId(), "");
        	
			for (Message message : messages) {
				UIDFolder uidFolder = (UIDFolder)message.getFolder();
				JSONObject messageJson = new JSONObject();
				
				messageJson.put("href", folderId + "/" + uidFolder.getUID(message));
				messageJson.put("folderId", folderId);
				messageJson.put("messageId", uidFolder.getUID(message));
				messageJson.put("fromemail", "");
								
				// importance
				String[] headers = message.getHeader("X-Priority");
				String header = headers != null ? headers[0] : "normal";
				int importance = 1;
				
				// startsWith is used since
				// there are cases like X-Priority: 1 (Highest) generated by Thunderbird.
				if (header.startsWith("1")) {
					importance = 2;
				} else if (header.startsWith("5")) {
					importance = 0;
				}
				
				messageJson.put("importance", importance);
				
				// Flagged is used for bookmark
				int flagged = 0;
				if (message.isSet(Flags.Flag.FLAGGED)) {
					flagged = 1;
				}
				messageJson.put("flag", flagged);
				
				// attachment
				boolean isAttached = IMAPAccess.hasAttachment(message);
				int attached = isAttached ? 1 : 0;
				messageJson.put("attach", attached);
				
				String addressStr = "";
							
				addressStr = ezEmailUtil.getFromNameOrAddressOfMessage(message);
				messageJson.put("sender", addressStr);
							
				// subject
				String subject = ezEmailUtil.getSubject(message);								
				subject = (subject != null) ? subject : "";
				
				if(subject.equals("")) {
					subject = egovMessageSource.getMessage("ezEmail.kms03", locale);					
				}
				
				messageJson.put("subject", subject);
				
				// received date
				Date receivedDate = message.getReceivedDate();
				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
				sdf.setTimeZone(TimeZone.getTimeZone("GMT"));
				
				String receivedDateStr = sdf.format(receivedDate);
	        	receivedDateStr = commonUtil.getDateStringInUTC(receivedDateStr, info.getOffSet(), false);
				
				messageJson.put("receivedt", receivedDateStr);
				
				// size
				messageJson.put("size", message.getSize());
				
				// read/unread
				int readFlag = message.isSet(Flags.Flag.SEEN) ? 1 : 0;
				messageJson.put("read", readFlag);
							
				if (message.isSet(Flags.Flag.ANSWERED)) {
					messageJson.put("contentclass", "REPLY");				
				} else {
					boolean isForwarded = ezEmailUtil.hasForwardedFlag(message);
					
					if (isForwarded) {
						messageJson.put("contentclass", "FORWARD");
					} else {
						messageJson.put("contentclass", "IPM.Note");
					}
				}
				
				messageJsonArray.add(messageJson);
			}
					
			folder.close(false);
		} catch (NumberFormatException e) {
			logger.error(e.getMessage(), e);
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		} finally {
			if (ia != null) {
				ia.close();
			}
		}
		
		return messageJsonArray;
	}

	@Override
	public int getMainMailUnreadCount(MCommonVO info, Locale locale) {
		IMAPAccess ia = null;
		
		String folderId = "INBOX";
		try {
		String domainName = ezCommonService.getTenantConfig("DomainName", info.getTenantId());
		String userEmail = info.getUserId() + "@" + domainName;
		String password = jspw;

		ia = IMAPAccess.getInstance(config.getProperty("config.MailServerAddress"), config.getProperty("config.IMAPPort"),
				userEmail, password, egovMessageSource, locale, ezEmailUtil);
				
		Folder folder = ia.getFolder(folderId);	
		return folder.getUnreadMessageCount();
		} catch (RuntimeException e) { 
		return -1;		
		} catch (Exception e) { 
		return -1;	
		}  finally {
			if (ia != null) {
				ia.close();
			}
		}
	}

	@SuppressWarnings("unchecked")
	@Override
	public JSONArray getFolderList(MCommonVO info, Locale locale, String folderId) {
		logger.debug("MEmailServiceImpl getFolderList started.");
		
		IMAPAccess ia = null;
//		List<MEmailFolderVO> mailFolderList = new ArrayList<MEmailFolderVO>();
		JSONArray malFolderList = new JSONArray();
		
		try {		
			logger.debug("folderId=" + folderId);		
	
			String domainName = ezCommonService.getTenantConfig("DomainName", info.getTenantId());
			String userEmail = info.getUserId() + "@" + domainName;
			String password = jspw;

			ia = IMAPAccess.getInstance(config.getProperty("config.MailServerAddress"), config.getProperty("config.IMAPPort"),
					userEmail, password, egovMessageSource, locale, ezEmailUtil);
			
			List<Folder> subMailFolder = null;
			
			if (folderId != null && !folderId.equals("")) {
				subMailFolder = ia.getSubFolders(folderId, true);
			} else {
				String useDefaultFoldersForLangOnly = ezCommonService.getTenantConfig("UseDefaultFoldersForLangOnly", info.getTenantId());
				boolean isUseDefaultFoldersForLangOnly = useDefaultFoldersForLangOnly.equals("YES") ? true : false;
				
				subMailFolder = ia.getTopLevelFolders(true, isUseDefaultFoldersForLangOnly);
			}
			
//			MEmailFolderVO folder = null;
			JSONObject folder = null;

			for (int i=0; i<subMailFolder.size(); i++) {
				Folder f = subMailFolder.get(i);
				folder = new JSONObject();	
//				folder = new MEmailFolderVO();
				folder.put("name", f.getName());
				folder.put("fullName", f.getFullName());
				folder.put("unreadCount", f.getUnreadMessageCount());
//				folder.setName(f.getName());
//				folder.setFullName(f.getFullName());
//				folder.setUnReadCount(f.getUnreadMessageCount());
				if (f.list().length > 0) {
					folder.put("hasSub", true);
//					folder.setHasSub(true);
				} else {
					folder.put("hasSub", false);
//					folder.setHasSub(false);
				}
//				mailFolderList.add(folder);
				malFolderList.add(folder);
			}
			
		} catch (RuntimeException e) {
			logger.error(e.getMessage(), e);
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		} finally {
			if (ia != null) {
				ia.close();
			}
		}
		
		logger.debug("MEmailServiceImpl getFolderList ended.");
		
		return malFolderList;
	}

}
