/* 테넌트 도메인 변경 스크립트 */
/* jmocha_mail_tag, jmocha_mail_tag_config의 james_user에 대한 FK를 제거후 변경하고 다시 FK 재설정 함 */
ALTER TABLE jmocha_mail_tag DROP CONSTRAINT jmocha_mail_tag_fk;
ALTER TABLE jmocha_mail_tag_config DROP CONSTRAINT jmocha_mail_tag_config_fk;
ALTER TABLE jmocha_distribution DROP CONSTRAINT fk_jmocha_distribution;
ALTER TABLE jmocha_mail_outofoffice_sent DROP CONSTRAINT fk_jmocha_outofoffice_sent;
UPDATE james_domain SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE james_mailbox SET USER_NAME = REPLACE(USER_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE james_recipient_rewrite SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE james_recipient_rewrite SET TARGET_ADDRESS = REPLACE(TARGET_ADDRESS, 'old.kaoni.com', 'new.kaoni.com');
UPDATE james_subscription SET USER_NAME = REPLACE(USER_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE james_user SET USER_NAME = REPLACE(USER_NAME, 'old.kaoni.com','new.kaoni.com');
UPDATE jmocha_address_folder SET owner_id = REPLACE(owner_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_address_general SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_address_info SET owner_id = REPLACE(owner_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_address_info SET creator_id = REPLACE(creator_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_address_simple SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_alias SET target_address = REPLACE(target_address, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_alias SET alias_address = REPLACE(alias_address, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_alias_retire SET target_address = REPLACE(target_address, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_alias_retire SET alias_address = REPLACE(alias_address, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_company_quota SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_default_quota SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_distribution SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_distribution SET MAIL = REPLACE(MAIL, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_distribution_sub SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_inbox_rule SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_inbox_rule_sub SET value = REPLACE(value, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_delete SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_forward SET userid = REPLACE(userid, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_general SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_outofoffice SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_outofoffice_sent SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_outofoffice_tem SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_pop3 SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_read SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_recall SET sender_email = REPLACE(sender_email, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_recall_detail SET receiver_email = REPLACE(receiver_email, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_reserve SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_secure SET user_name = REPLACE(user_name, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_secure_read SET reader_id = REPLACE(reader_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_signature SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_tag SET user_name = REPLACE(user_name, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_mail_tag_config SET user_name = REPLACE(user_name, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_storage_warning_sent SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_user_dist_apply SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_user_distribution SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_user_distribution_mem SET DOMAIN_NAME = REPLACE(DOMAIN_NAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_user_mail_template SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
UPDATE jmocha_user_quota SET user_id = REPLACE(user_id, 'old.kaoni.com', 'new.kaoni.com');
/* serverName 설정은 서버명이 들어가야 하므로 주의 필요 */
UPDATE tbl_tenant_config SET PROPERTY_VALUE = REPLACE(PROPERTY_VALUE, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_company_config SET PROPERTY_VALUE = REPLACE(PROPERTY_VALUE, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_deptmaster SET MAIL = REPLACE(MAIL, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster SET MAIL = REPLACE(MAIL, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster SET UPNNAME = REPLACE(UPNNAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster_retire SET MAIL = REPLACE(MAIL, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster_retire SET UPNNAME = REPLACE(UPNNAME, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster_delete SET MAIL = REPLACE(MAIL, 'old.kaoni.com', 'new.kaoni.com');
UPDATE tbl_usermaster_delete SET UPNNAME = REPLACE(UPNNAME, 'old.kaoni.com', 'new.kaoni.com');
ALTER TABLE jmocha_mail_tag ADD CONSTRAINT jmocha_mail_tag_fk FOREIGN KEY (user_name) REFERENCES james_user(user_name) ON DELETE CASCADE;
ALTER TABLE jmocha_mail_tag_config ADD CONSTRAINT jmocha_mail_tag_config_fk FOREIGN KEY (user_name) REFERENCES james_user(user_name) ON DELETE CASCADE;
ALTER TABLE jmocha_distribution_sub ADD CONSTRAINT fk_distribution_sub FOREIGN KEY (domain_name, user_name) REFERENCES jmocha_distribution(domain_name, user_name) ON DELETE CASCADE ENABLE;
ALTER TABLE jmocha_mail_outofoffice_sent ADD CONSTRAINT fk_jmocha_outofoffice_sent FOREIGN KEY (user_id) REFERENCES jmocha_mail_outofoffice(user_id) ON DELETE CASCADE ENABLE;
-- tbl_tenant_config에서 PROPERTY_NAME like '%omain%', PROPERTY_VALUE  like '%old%' 확인
