-- 2024.04.01 장혜연  테넌트 삭제 스크립트
-- tenantId, tenantDomainName 변수 선언
SET @tenant_id_value = 0;
SET @tenant_domain_value = 'jtest.kaoni.com';
-- tenant domain이 full 주소로 있을 경우 %@ -- 로 삭제 
SET @tenant_domain_full_value = CONCAT('%@','jtest.kaoni.com');

DELETE FROM TBL_TENANT_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TENANT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DEPTMASTER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERMASTER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JAMES_DOMAIN WHERE DOMAIN_NAME IN
(SELECT DISTINCT JRR.DOMAIN_NAME FROM JAMES_RECIPIENT_REWRITE AS JRR JOIN JMOCHA_ALIAS AS JA
ON JRR.TARGET_ADDRESS = JA.TARGET_ADDRESS WHERE JA.TARGET_ADDRESS LIKE @tenant_domain_full_value);

DELETE FROM JAMES_RECIPIENT_REWRITE WHERE DOMAIN_NAME IN
(SELECT DISTINCT JRR.DOMAIN_NAME FROM JAMES_RECIPIENT_REWRITE AS JRR JOIN JMOCHA_ALIAS AS JA
ON JRR.TARGET_ADDRESS = JA.TARGET_ADDRESS WHERE JA.TARGET_ADDRESS LIKE @tenant_domain_full_value);

DELETE FROM JAMES_DOMAIN WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JAMES_RECIPIENT_REWRITE WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_MAIL_TAG_CONFIG WHERE USER_NAME LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_TAG WHERE USER_NAME LIKE @tenant_domain_full_value;

DELETE FROM JAMES_USER WHERE USER_NAME LIKE @tenant_domain_full_value;

DELETE FROM JAMES_MAILBOX WHERE USER_NAME LIKE @tenant_domain_full_value;

DELETE FROM JAMES_SUBSCRIPTION WHERE USER_NAME LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_DEFAULT_QUOTA WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_COMPANY_QUOTA WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_ADDRESS_FOLDER WHERE OWNER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_ADDRESS_GENERAL WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_ADDRESS_SIMPLE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_ADDRESS_INFO WHERE OWNER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_ALIAS WHERE TARGET_ADDRESS LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_BIGATTACH_DOWN_LIMIT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_DEPT_MASTER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_INBOX_RULE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_LETTERBOX WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_MAIL_COLOR WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_MAIL_DELETE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_FORWARD WHERE USERID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_GENERAL WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_OUTOFOFFICE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_OUTOFOFFICE_TEM WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_POP3 WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_READ WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_RECALL WHERE SENDER_EMAIL LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_SIGNATURE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_MAIL_SIGNATURE_TEMPLATE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_CONNECTION_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_MAIL_COPYRIGHT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_MAILBOX_PROGRESS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_SHARED_MAILBOX WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAIL_COMPANY_FLOW_DAY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAIL_COMPANY_FLOW_MONTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAIL_LOG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAIL_USER_DAY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAIL_USER_MONTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STAT_MAILBOXQTY_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM JMOCHA_STORAGE_WARNING_SENT WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_USER_DIST_APPLY WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_USER_DISTRIBUTION WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_USER_DISTRIBUTION_MEM WHERE DOMAIN_NAME = @tenant_domain_value;

DELETE FROM JMOCHA_USER_MAIL_TEMPLATE WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_USER_QUOTA WHERE USER_ID LIKE @tenant_domain_full_value;

DELETE FROM JMOCHA_USER_LOCAL_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ACCESS_COUNTRY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ACCESS_ID WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ACCESS_IP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ADDJOBMASTER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ADMIN_ACCESS_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ADMIN_ACCESS_IP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ADMINRECEIPTGROUP_MAIN WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ADMINRECEIPTGROUP_SUB WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRBIGATTACH_DOWNLOADINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRDOCATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRDOCGROUPINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRLINEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APROPINIONINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRPREVIEW WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_APRRECEIPTPROCESSINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTENDANT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_ANNUAL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_ANNUAL_CANAPPL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_ANNUAL_CONF WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_ANNUAL_HISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_APR_CONN WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_AUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_MODAPPL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_MODAPPL_HISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_AUDIO_VISUALRECEXINFO_TEMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_AUDIO_VISUALRECEXINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHISTORY_REC WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECORDHISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SEPERATEATTACH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_AUDITAPPRLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_AUTODOCNUM_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_APPRLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_BOARDBACKGROUNDINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_BOARDINFO_ATTRIBUTE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_BOARDMANAGE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_CONFIGURATION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_DELETERESERVEDBOARD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_DELETERESERVEDITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM_ATTACHMENTS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM_LISTOPTION_BOAR WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM_READ WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM_TEMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_LIKE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_MYTREE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_NEWBOARD_ORDERINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_NOTICEBOARD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ONELINEREPLY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_REPLY_REACT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_TABBOARD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_TREECACHE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_BOARD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_CLUB WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_CLUBGUEST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_CLUBNOTICE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_CLUBUSER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_COMCLOSE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_MEMBERINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_NOTICE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_OUTAPPLICATION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_POLLANSWER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_POLLMANAGER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_POLLQUESTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_POLLRESPONSE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABINET_VIEWAUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABINET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHISTORY_CAB WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABINETHISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABROLEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_OLDCABINETEXTRAINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SPECIALCATALOGINFO_CAB WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABINETCLASS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CAR_ACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CAR_ATTACH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CAR_FORM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_ADMIN_MODULE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_ATTACH_FILE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_CABINET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_COMPANY_CAPACITY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_REL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_RELATION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_SHARE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_USER_CAPACITY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CB_USER_MODULE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_BM WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_BMUSER WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_COMMENT WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_COMMENTSTATE WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_FILE WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_FOLDER WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_LINK WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_OPTION WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_USER WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_CLUBID WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_BOARDINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_BOARDMANAGE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_DELETERESERVEDBOARD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_DELETERESERVEDITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_ITEM_ATTACHMENTS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_ITEM_READ WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_MYBOARDS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_ONELINEREPLY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_SECRETARY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMM_TREECACHE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CONNECTION_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CONTAINER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CONTAINERUSEDEP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DAILYDOCCOUNTLOG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DAILYFORMCOUNTLOG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DELETECABINETINFO WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_DEPT_CHANGE_INFO WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_DEPTCONTLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DEPTCONT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DEPTTEMPLET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DEPTTEMPLETDETAIL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DEV_MASTER WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_DOCDELETEHISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_DOCDELIVERY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_EDITAPPRDOC WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ENDAPRDOCATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ENDATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ENDRECEIPTPOINTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_EXPAPRDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_EXPAPRLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_EXPENDAPRDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_EXPENDAPRLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORM_AUTORULE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORM_AUTORULELINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMCONTUSERGROUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMGROUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMRECV WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMUSERINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_GONGRAMLINEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_HISTORYATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_HISTORYDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_HISTORYLINEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_HISTORYRECEIPTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_HOLIDAYLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_FORM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_AUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_ENV WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_FORM_TYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_ORDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_RECV_FAVORITE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LADDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LADDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LADDER_BM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LASTAPRLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LASTDEPTLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LASTDOCID WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LINTEMPLET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LINTEMPLETDETAIL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LOGO_SIZE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LUNARUSE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_MEMO_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_MEMO_FOLDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_MOBILEOPTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_MYTASKCODE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_NOTIFICATION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SPECIALCATALOGINFO_REC WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECORD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_OPENGOVFILEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PASSWORD_POLICY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PASSWORD_POLICY_PATTERN WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PERMISSION_CHANGE_INFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PERMISSIONGROUPLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PHOTO_IMAGEITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_ITEM_ATTACHMENT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_ITEM_READ WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_GROUPMEMBER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_COMMENT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_ITEM_LIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_PRETASKREL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_TASKMEMBER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_LOG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_FAVORITE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_MAINLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_TASK WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_GROUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_MEMBER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_BOARD_FOLDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_PROJECT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PMS_SETTING WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_ANSWER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_ATTACH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_ITEMACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_ITEMREAD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_PERMISSION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_QUESTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_RESPONSE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_RESPONSEPERSON WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_POLL_TABLE_ANSWER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_ACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_LOGO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PREVIOSLYREGI WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_PORTLET_USER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PROXYINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_APPROVNOTIMAILCONF WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_EMPMONTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_LIGHTPOLL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_LIGHTPOLL_OPTION WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_PS_LIGHTPOLLRESULT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_NOTICE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_POPUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_POPUP_OPTION WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_PS_POPUP_USER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_QUICKLINK WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_QUICKLINK_ACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_SHAREAPPROVAL WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_PS_SLIDERIMAGE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_USERWEBPART WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_WEBPARTGROUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_WEBPARTITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PS_WEBPARTITEMACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PWDINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_QS_ITEMSEQ WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECEIPTPOINTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECEXCHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECORD_TEMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECREADHISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECRELAYATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECRELAYINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECRELAYSIGNINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECROLEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RECROLEINFO_TEMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_FAVORITE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_PERSPORTLET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_RESACL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_SCHEDULE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_SCHEDULEFORM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_SCHEDULEREPETITION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULE_COMPLETE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULE_OAUTHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULE_PUBLIC_DEPT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULEATTACH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULECONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULEGROUP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULEGROUPMEMBER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SCHEDULEREPETITION_DEL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SEALDEPTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SEALINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SECRETARY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SENDOUTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SEPERATEATTACH_TEMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SERIAL_NOROLLBACK WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SERIALNUMGEN WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SERIALNUMGEN_GRANT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SHARE_DOC_DIR WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SIGNINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SPECIALCATALOGINFO_TMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SPECIALCONTAINERINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SURVEY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SURVEY_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_SUSINSCHEDULE WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASK WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASK_DEPTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKATTACH WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASKCODEHISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKCOMMENT WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASKCONFIG WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASKGENERAL WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASKINSTANCESTATUS WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_TASKSHARE WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_THEME_GENERAL WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPAPRDOCATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPAPRDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPAPRLINEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPAPROPINIONINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPATTACHINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPEXPAPRDOCINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPEXPAPRLINE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TMPRECEIPTPOINTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USER_CHANGE_INFO WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_USER_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USER_JOBMASTER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USER_LISTOPTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USER_MULTILOGIN WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USER_NOTI_DISABLE_ITEM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERCONTLIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERCONT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERLOCALINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERMASTER_DELETE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERMASTER_RETIRE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_USERMOBILEINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_ANSWER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_COMMENT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_CONFIGURATION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_QUESTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_QUESTION_RELATED WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_USER_AND_ANSWER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_VOTE_USER_AND_QUESTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEATHER_USER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_APPLY_HISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_ENC_FOLDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_ENCRYPTED_FILE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_ENV WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FAVOR WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FILE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FILE_HISTORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FILETYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FILEUSER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FOLDER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FOLDERUSER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_LOG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_NO_INHERIT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_SHARE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_TOKEN WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_USER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_YEARLYDOCCOUNT WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TENANT_SERVERNAME WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_COMPANY_CONFIG WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_ITEM_LISTOPTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_BOARDINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_BOARD_MYBOARDS WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_C_CATEGORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKCODE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKSUBCATEGORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKMIDDLECATEGORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_TASKCATEGORY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LASTDOCID WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CONTAINERTODOCSTATE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMPROPERTY WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CODELIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LISTOPTION WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_LISTINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CABINETCODELIST WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMCONNINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMCONTAINER WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CONTAINERTYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CIRCULAR_LISTOPTION WHERE TENANTID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_FORM_TYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_JOURNAL_FORM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_WEBFOLDER_FILETYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_FORM WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_CONF WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_ATTITUDE_TYPE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORM_OFFICE WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_FORMINFO WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_MENU_COMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_MENU_AUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_MENU_NAME WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_PORTLET_COMP WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_PORTLET_NAME WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_THEME_PORTLET WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_THEME_AUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_PORTAL_PORTLET_AUTH WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_RS_BRD WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_CAR WHERE TENANT_ID = @tenant_id_value;

DELETE FROM TBL_GONGRAMDELETEHISTORY WHERE TENANT_ID = @tenant_id_value;
