/*
 Copyright (c) 2013, Raonwiz Technology Inc. All rights reserved.
*/
window.DEXT5||(window.DEXT5=function(){return{isRelease:!0,isPopUpCssLoaded:!1,version:"DEXT5 Editor",ReleaseVer:"3.5.1056405.2143.01",ServerReleaseVer:"",cabVersion:"3,6,0,14",rootPath:function(){var b=window.DEXT5_ROOTPATH||"";if(!b)for(var c=document.getElementsByTagName("script"),a=c.length,d=null,h=0;h<a;h++){var d=c[h],f=d.src.match(/(^|.*[\\\/])dext5editor.js(?:\?.*)?$/i);"samsung.net"==document.domain&&(f=d.src.match(/(^|.*[\\\/])helloeditor.js(?:\?.*)?$/i));if(f){b=f[1];break}}-1==b.indexOf(":/")&&
(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+b:location.href.match(/^[^\?]*\/(?:)/)[0]+b);b=b.substring(0,b.length-1);b=b.substring(0,b.lastIndexOf("/"))+"/";if(!b)throw"DEXT5 Editor installation path could not be automatically detected.";return b}(),getUrl:function(b){-1==b.indexOf(":/")&&0!==b.indexOf("/")&&(b=this.rootPath+b);this.ReleaseVer&&"/"!=b.charAt(b.length-1)&&!/[&?]ver=/.test(b)&&(b+=(0<=b.indexOf("?")?"&":"?")+"ver="+this.ReleaseVer);return b},DEXTMULTIPLE:{},DEXTHOLDER:{},
ShowTextChangeAlert:!0}}(),DEXT5.brower||(DEXT5.browser=function(){var b=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<b.search("trident")||-1<b.search("msie")||-1<b.search("edge/12")?!0:!1,opera:!!c&&c.version,webkit:-1<b.indexOf(" applewebkit/"),mac:-1<b.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<b.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(b),isCustomDomain:function(){if(!this.ie)return!1;var a=document.domain,b=window.location.hostname;return a!=b&&
a!="["+b+"]"},isHttps:"https:"==location.protocol};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.ie&&(c.gecko=!1);c.webkit&&(-1<b.indexOf("chrome")?(c.chrome=!0,-1<b.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var a;c.ieVersion=0;c.ie&&(a=c.quirks||!document.documentMode?-1<b.indexOf("msie")?parseFloat(b.match(/msie (\d+)/)[1]):-1<b.indexOf("trident")?parseFloat(b.match(/rv:([\d\.]+)/)[1]):-1<b.indexOf("edge/12")?12:7:document.documentMode,c.ieVersion=a,c.ie12=12==a,c.ie11=
11==a,c.ie10=10==a,c.ie9=9==a,c.ie8=8==a,c.ie7=7==a,c.ie6=7>a||c.quirks,-1<b.indexOf("trident")?c.trident=parseFloat(b.match(/ trident\/(\d+)/)[1]):c.trident="");c.gecko&&(a=b.match(/rv:([\d\.]+)/))&&(a=a[1].split("."),a=1E4*a[0]+100*(a[1]||0)+1*(a[2]||0));c.webkit&&(a=parseFloat(b.match(/ applewebkit\/(\d+)/)[1]));return c}()));
DEXT5.config={Width:"",Height:"",SkinName:"",InitXml:"",InitServerXml:"",ToSavePathURL:"",ToSaveFilePathURL:"",ServerDomain:"",HandlerUrl:"",InitVisible:!0,DefaultMessage:"",FirstLoadType:"",FirstLoadMessage:"",FileFieldID:"",EditorHolder:"",zTopMenu:"",zToolBar:"",zTopStatusBar:"",zStatusBar:"",zXssUse:"",zXssRemoveTags:"",zXssRemoveEvents:"",Mode:"",zIndex:"",NextTabElementId:"",IgnoreSameEditorName:"0",ChangeMultiValueMode:"",EditorBorder:"",InitLang:"",Lang:"",IconName:"icon",CustomCode:"",EnterTag:"",
userFontFamily:"",userFontSize:"",UserFieldID:"",UserFieldValue:"",LicenseKey:"",mimeCharset:"",mimeConentEncodingType:"",mimeFileTypeFilter:"",mimeLocalOnly:"",mimeRemoveHeader:"",userOpenDlgTitle:"",userOpenDlgType:"",userOpenDlgInitDir:"",userImageDlgStyle:"",mimeBaseURL:"",focusInitObjId:"",focusInitEditorObjId:"",tabIndexObjId:"",pluginUse:"",imageEditorUse:"",mimeUse:"",officeLineFix:"",useLog:"0",RootPath:"",EditorTabDisable:"",FormListUrl:"",RunTimes:"",MouseEventCancel:!1,KeyEventCancel:!1,
SetValueObjId:"",LoadedEvent:"",scrollOverflow:"",DocType:"",DevelopLangage:"",UnitDelimiter:"",UnitAttributeDelimiter:"",EditorBodyEditable:"",SymbolUrl:"",AccessibilityValidationItems:"",ViewModeAutoHeight:"",ViewModeAutoWidth:"",ShowDialogPosition:"",StatusBarItem:"",StatusBarInitMode:"",ImageBaseUrl:"",DragResize:"",DragResizeApplyBrowser:"",ReplaceOutsideImage:"",ReplaceOutsideImageExceptDomain:"",RemoveItem:"",RemoveContextItem:"",FormMode:"",BodyOutsideCodeCut:"",EventList:"",TableLock:{Use:"",
LockName:"",ShowLockIconUserMode:"",TableLockMode:""},FontFamilyList:"",FontSizeList:"",LineHeightList:"",FormattingList:"",FrameFullScreen:"",DialogWindow:null};
DEXT5.ajax=function(){var b=function(){if(!DEXT5.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},a=function(a){return c(a)?a.responseText:null},d=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
h=function(a,c,g){var e=!!c,d=b();if(!d)return null;d.open("GET",a,e);e&&(d.onreadystatechange=function(){4==d.readyState&&(c(g(d)),d=null)});try{d.send(null)}catch(h){return null}setTimeout(function(){d.abort()},5E3);return e?"":g(d)};return{load:function(b,c){return h(b,c,a)},loadXml:function(a,b){return h(a,b,d)},postData:function(a,c){var d;a:if(d=b()){try{d.open("POST",a,!1),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),d.send(c)}catch(e){d=null;break a}d=
d.responseText}else d=null;return d},postFileData:function(a,c){var d;a:if(d=b()){try{d.open("POST",a,!1);var e="--------------------"+(new Date).getTime();d.setRequestHeader("Content-Type","multipart/form-data; boundary="+e);for(var e="--"+e,h="",n=c.split("&"),p=n.length,m=null,t="",x="",w=0;w<p;w++)m=n[w].split("="),"imagedata"==m[0]?t=m[1]:(h+=e+"\r\n",h+='Content-Disposition: form-data; name="'+m[0]+'"\r\n\r\n',h+=m[1]+"\r\n");for(var n=null,p="",y=window.atob(t),F=y.length,n=new Uint8Array(new ArrayBuffer(F)),
w=0;w<F;w++)n[w]=y.charCodeAt(w),p+=String.fromCharCode(n[w]);String.fromCharCode.apply([],new Uint8Array(n));new Uint8Array(n);x=p;h+=e+"\r\n";h+='Content-Disposition: form-data; name="Filedata"; filename="'+(new Date).getTime()+'"\r\n';h+="Content-Type: image/png\r\n";h+="\r\n";h+=x+"\r\n";d.send(h+(e+"--\r\n"))}catch(Y){d=null;break a}d=d.responseText}else d=null;return d}}}();
DEXT5.util={G_IMG_LIST:{},trim:function(b){return b.trim?b.trim():b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},setClass:function(b,c){b.className=c},getClass:function(b){return b.className},checkUrl:function(b){var c=!1;return c=(new RegExp(/(http|ftp|https|news):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/)).test(b)},makeIframe:function(){var b;try{b=document.createElement('<iframe frameborder="0" >')}catch(c){b=document.createElement("iframe")}b.style.margin="0px";b.style.padding=
"0px";b.frameBorder=0;b.style.overflow="auto";b.style.overflowX="hidden";b.style.backgroundColor="#ffffff";return b},addEvent:function(b,c,a,d){b.addEventListener?b.addEventListener(c,a,d):b.attachEvent&&b.attachEvent("on"+c,a)},removeEvent:function(b,c,a,d){b.removeEventListener?b.removeEventListener(c,a,d):b.detachEvent&&b.detachEvent("on"+c,a)},stopEvent:function(b){"bubbles"in b?b.bubbles&&b.stopPropagation():b.cancelBubble=!0},cancelEvent:function(b){b.preventDefault?b.preventDefault():b.returnValue=
!1},ajax:{xml_http_request:function(){var b;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));return b}},url:{full_url:function(b){var c="";if(0==b.indexOf("http://")||0==b.indexOf("https://"))c=b;else if(0==b.indexOf("/"))c=location.protocol+"//"+location.host+b;else var c=location.href,a=c.lastIndexOf("/"),c=c.substring(0,a+1),c=c+b;return c}},xml:{count:function(b,c){return b?b.getElementsByTagName(c).length:0},getNode:function(b,c){return null==
b||void 0==b?null:this.getNodeIdx(b,c,0)},getNodeIdx:function(b,c,a){return b.getElementsByTagName(c)[a]},getNodeValue:function(b,c){return null==b||void 0==b?"":this.getNodeValueIdx(b,c,0)},getNodeValueIdx:function(b,c,a){b=this.getNodeIdx(b,c,a);return this.getValue(b)},getValue:function(b){var c="",a="";if(void 0!=b)try{0<b.childNodes.length&&(a=c=b.firstChild.nodeValue);try{("product_key"==b.nodeName||"font"==b.nodeName||"encoding"==b.nodeName||"doctype"==b.nodeName)&&2<=b.childNodes.length&&
(c=b.textContent?b.textContent:a)}catch(d){c=a}}catch(h){c="parsing error"}return c}},htmlToLowerCase:function(b){if(8<DEXTTOP.DEXT5.browser.ieVersion&&0==DEXTTOP.DEXT5.browser.quirks)return b;var c=RegExp("<[^>]+>","g");results=b.match(c);if(null==results)return b;var a=c=-1,d=0,h=results.length;for(i=0;i<h;i++){original=results[i];c=original.indexOf("'");a=original.indexOf('"');d=2;1<c*a&&(-1<original.indexOf('="')?(results[i]=results[i].replace(/\'/g,"dext5_1q"),d=2):-1<original.indexOf("='")&&
(results[i]=results[i].replace(/\"/g,"dext5_2q"),d=1));stripquoted=1==d?results[i].replace(/ [^=]+= *\'[^\']*\'/g,""):results[i].replace(/ [^=]+= *"[^"]*"/g,"");c=RegExp(" [^=]+=[^ >]+","g");if(unquoted=stripquoted.match(c))for(c=unquoted.length,j=0;j<c;j++)addquotes=1==d?unquoted[j].replace(/( [^=]+=)([^ >]+)/g,"$1'$2'"):unquoted[j].replace(/( [^=]+=)([^ >]+)/g,'$1"$2"'),results[i]=results[i].replace(unquoted[j],addquotes);results[i]=results[i].replace(/<\/?[^>|^ ]+/,function(a){return a.toLowerCase()});
results[i]=1==d?results[i].replace(/ [^=|^ ]+=\'/g,function(a){return a.toLowerCase()}):results[i].replace(/ [^=|^ ]+="/g,function(a){return a.toLowerCase()});results[i]=results[i].replace(/dext5_1q/g,"'");results[i]=results[i].replace(/dext5_2q/g,'"');b=b.replace(original,results[i])}return b},hexDigits:"0123456789abcdef".split(""),hex:function(b){return isNaN(b)?"00":this.hexDigits[(b-b%16)/16]+this.hexDigits[b%16]},rgb2hex:function(b){b=b.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);if(!(null==b||
4>b.length))return"#"+this.hex(b[1])+this.hex(b[2])+this.hex(b[3])},dextSetAttribute:function(b,c,a,d){"string"==typeof a?0<a.length&&(b.style[c]=a+d):"number"==typeof a&&(b.style[c]=a)},getRealBackgoundImagePath:function(b){return b=b.replace(/url\(\s*(["']?)\s*([^\)]*)\s*\1\s*\)/i,function(b,a,d){return d})},replaceForXSS:function(b,c,a,d){var h=!1;try{if(""!=a)for(var f=a.split(","),k=f.length,g=0;g<k;g++){var e=f[g],r=new RegExp("<"+e+"[^>]*>[\\s\\S]*?</"+e+">","gim");1==r.test(b)&&(h=!0,b=b.replace(r,
""));var n=new RegExp("<"+e+"[^>]*>","gi");1==n.test(b)&&(h=!0,b=b.replace(n,""))}if(""!=d)for(var p=d.split(","),m=p.length,g=0;g<m;g++){var t=p[g],x=new RegExp("(?:"+t+')\\s*=\\s*"[^"]*"\\s*',"gi"),w=new RegExp("(?:"+t+")\\s*=\\s*'[^']*'\\s*","gi");if(x.test(b)||w.test(b))h=!0,b=b.replace(x,""),b=b.replace(w,"")}if(""!=c)for(var y=c.split(","),F=y.length,g=0;g<F;g++){var Y=new RegExp("<\\/"+y[g]+">","gi"),G=b.match(new RegExp("<"+y[g]+"[^>]*>","gi"));if(G){var h=!0,da=G.length;c="";for(a=0;a<da;a++)c=
G[a].toLowerCase(),c=c.replace("<","&lt;"),c=c.replace(">","&gt;"),b=b.replace(G[a],c);b=b.replace(Y,"&lt;/"+y[g]+"&gt;")}}}catch(ta){}0==h&&(b="");return b},removeTags:function(b,c){for(var a=c.split(","),d=null,h=a.length,f=0,k=0;k<h;k++)for(d=b.getElementsByTagName(a[k]),f=d.length,--f;0<=f;f--){var g=d[f];g.parentNode.removeChild(g)}},removeEvents:function(b,c,a){b=c.split(",");c=a.length;for(var d=0,h=0;h<c;h++)for(var d=b.length,f=0;f<d;f++)a[h].removeAttribute(b[f])},removeElement:function(b){for(;b.firstChild;)b.parentNode.insertBefore(b.firstChild,
b);b.parentNode.removeChild(b)},officeClean:function(b,c){if(""==b||void 0==b)return"";var a=null,d=[],h=!1;/([:| ])([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)pt/gi.test(b)&&(h=!0);/([:| ])([:| ][-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)cm/gi.test(b)&&(h=!0);if(1==h){h=document.createElement("div");h.innerHTML=b;for(var a=h.getElementsByTagName("*"),d=a.length,f=0;f<d;f++){var k=a[f];if(k.style.width){var g=k.style.width.toLowerCase();-1<g.indexOf("pt")?(g=4*parseFloat(g)/3,0<g&&1>g&&(g=1),0>g&&(g=
0),g=Math.round(g)+"px",k.style.width=g):-1<g.indexOf("cm")&&(_cm=37.795275593333*parseFloat(g),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),g=Math.round(_cm)+"px",k.style.width=g)}k.style.height&&(g=k.style.height.toLowerCase(),-1<g.indexOf("pt")?(g=4*parseFloat(g)/3,0<g&&1>g&&(g=1),0>g&&(g=0),g=Math.round(g)+"px",k.style.height=g):-1<g.indexOf("cm")&&(_cm=37.795275593333*parseFloat(g),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),g=Math.round(_cm)+"px",k.style.height=g));g="";k.style.borderStyle&&(g=k.style.borderStyle);
""!=k.style.borderTop&&(k.style.borderTop=replacePtOrCmToPx(k.style.borderTop));""!=k.style.borderRight&&(k.style.borderRight=replacePtOrCmToPx(k.style.borderRight));""!=k.style.borderBottom&&(k.style.borderBottom=replacePtOrCmToPx(k.style.borderBottom));""!=k.style.borderLeft&&(k.style.borderLeft=replacePtOrCmToPx(k.style.borderLeft));""!=k.style.borderWidth&&(k.style.borderWidth=replacePtOrCmToPx(k.style.borderWidth));""!=g&&(k.style.borderStyle=g)}b=h.innerHTML}b=b.replace(/\.0px/g,"px");b=b.replace(/\t/g,
"");b=DEXT5.util.removeOfficeDummyTag(b,"\x3c!--[if supportFields]>","<![endif]--\x3e");a=RegExp("<o:p></o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p>\\s+</o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)></o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");b=b.replace(a,"");b=b.replace(/\slang=[\"]?en-us[\"]?/gi,"");b=b.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,"");a=RegExp('mso-[^:]+:[^;">]+;',"gi");b=b.replace(a,"");a=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");b=b.replace(a,"$1");
b=DEXT5.util.replaceAll(b,"hairline","dotted");for(h=0;5>h;h++){d=["o:p","span","font"];k=d.length;for(f=0;f<k;f++)a=new RegExp("<"+d[f]+"[^>]*></"+d[f]+">","gi"),b=b.replace(a,""),a=new RegExp("<"+d[f]+"[^>]*>&nbsp;</"+d[f]+">","gi"),b=b.replace(a,"&nbsp;"),"span"!=d[f]&&(a=new RegExp("<"+d[f]+"[^>]*> </"+d[f]+">","gi"),b=b.replace(a,"&nbsp;"));d=["o","v","w","m","x"];k=d.length;for(f=0;f<k;f++)0==f&&(b=b.replace(/<o:p/gi,"<dexto:p")),a=new RegExp("<"+d[f]+":[^/>]+/>","gi"),b=b.replace(a,""),a=new RegExp("<"+
d[f]+":[^>]+>[^<]*</"+d[f]+":[^>]+>","gi"),b=b.replace(a,""),f==k-1&&(b=b.replace(/<dexto:p/gi,"<o:p"))}b=b.replace(/style=""/gi,"");b=b.replace(/style=''/gi,"");b=b.replace(/\s>/gi,">");b=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(b);b=b.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");b=b.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");b=b.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");b=b.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){var a=b.length,
f=d=!1,e=g=k="";if(-1==b.indexOf("<")&&-1==b.indexOf(">"))for(h=0;h<a;h++)k=b.charAt(h),g=b.charAt(h+1)," "!=k&&32!=k.charCodeAt(0)||" "!=g&&32!=g.charCodeAt(0)||(k="&nbsp;"),e+=k;else for(h=0;h<a;h++)k=b.charAt(h),g=b.charAt(h+1),"<"==k?(d=!1,f="p"==g.toLowerCase()?!0:!1):">"==k&&1==f?d=!0:1!=d||" "!=k&&32!=k.charCodeAt(0)||" "!=g&&32!=g.charCodeAt(0)||(k="&nbsp;"),e+=k;b=e}0==c&&(b=DEXTTOP.DEXT5.util.removeLocalFileImage(b));return b},removeLocalFileImage:function(b){if(""==b||void 0==b)return"";
b=b.replace(/file:\/\/\//gi,"dext_local_file_image");reg_exp=RegExp("<img[^>]+dext_local_file_image[^>]+>","gi");return b=b.replace(reg_exp,"")},html2xhtml:function(b){if(""==b||void 0==b)return"";for(var c="area base br col embed frame hr img input link meta param".split(" "),a=c.length,d=null,h=RegExp(),f=0;f<a;f++)d=c[f],h=new RegExp("<"+d+" ([^>]*)>","gi"),b=b.replace(h,"<"+d+" $1 />"),h=new RegExp("<"+d+">","gi"),b=b.replace(h,"<"+d+" />");return b},emptyTagRemove:function(b){if(""==b||void 0==
b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var c=document.createElement("div");c.innerHTML=b;for(var a=c.getElementsByTagName("p"),d=a.length,h,f,k="",g=[],e=["br","img","a","hr","table"],r=!1,n=0;n<d;n++)if(h=a[n],k="textContent"in h?h.textContent:h.innerText,""==k){f=h.innerHTML;for(var r=!1,p=e.length,m=0;m<p;m++)if(-1<f.toLowerCase().indexOf("<"+e[m])){r=!0;break}0==r&&g.push(h)}for(var t=g.length;0<t;)h=g.pop(),h.parentNode.removeChild(h);b=c.innerHTML}}catch(x){}return b},
emptyTagRemoveCheckInContentTag:function(b,c){if(""==b||void 0==b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var a=document.createElement("div");a.innerHTML=b;for(var d=a.getElementsByTagName("p"),h=d.length,f,k,g="",e=[],r=!1,n=0;n<h;n++)if(f=d[n],g="textContent"in f?f.textContent:f.innerText,""==g){k=f.innerHTML;for(var r=!1,p=c.length,m=0;m<p;m++)if(-1<k.toLowerCase().indexOf("<"+c[m])){r=!0;break}0==r&&e.push(f)}for(var t=e.length;0<t;)f=e.pop(),a.removeChild(f);b=a.innerHTML}}catch(x){}return b},
htmlRevision:function(b,c){if(""==b||void 0==b)return"";var a=null;b=b.replace(/\x3c!--[\w\s\d@{}:.;,'"%!#_=&|?~()[*+\/\-\]]*--\x3e/gi,"");DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=RegExp("><p><br></p></td>","gi"),b=b.replace(a,"><p>&nbsp;</p></td>")):(a=RegExp(">&nbsp;</td>","gi"),b=b.replace(a,"><p><br></p></td>"));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=RegExp("<p><br></p>","gi"),b=b.replace(a,"<p>&nbsp;</p>"),a=RegExp("<p><br/></p>","gi"),b=b.replace(a,"<p>&nbsp;</p>"),a=RegExp("<p><br /></p>",
"gi"),b=b.replace(a,"<p>&nbsp;</p>"),a=RegExp("<p></p>","gi"),b=b.replace(a,"<p>&nbsp;</p>"),a=RegExp("<p>\\s+</p>","gi"),b=b.replace(a,"<p>&nbsp;</p>"),a=RegExp("<p ([^>]+)><br></p>","gi"),b=b.replace(a,"<p $1>&nbsp;</p>"),a=RegExp("<p ([^>]+)><br/></p>","gi"),b=b.replace(a,"<p $1>&nbsp;</p>"),a=RegExp("<p ([^>]+)><br /></p>","gi"),b=b.replace(a,"<p $1>&nbsp;</p>"),a=RegExp("<p ([^>]+)></p>","gi"),b=b.replace(a,"<p $1>&nbsp;</p>"),a=RegExp("<p ([^>]+)>\\s+</p>","gi"),b=b.replace(a,"<p $1>&nbsp;</p>")):
(a=RegExp("<p></p>","gi"),b=b.replace(a,"<p><br></p>"),a=RegExp("<p>&nbsp;</p>","gi"),b=b.replace(a,"<p><br></p>"),a=RegExp("<p>\\s+</p>","gi"),b=b.replace(a,"<p><br></p>"),a=RegExp("<p ([^>]+)></p>","gi"),b=b.replace(a,"<p $1><br></p>"),a=RegExp("<p ([^>]+)>&nbsp;</p>","gi"),b=b.replace(a,"<p $1><br></p>"),a=RegExp("<p ([^>]+)>\\s+</p>","gi"),b=b.replace(a,"<p $1><br></p>"));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=RegExp("<div><br></div>","gi"),b=b.replace(a,"<div>&nbsp;</div>"),a=RegExp("<div><br/></div>",
"gi"),b=b.replace(a,"<div>&nbsp;</div>"),a=RegExp("<div><br /></div>","gi"),b=b.replace(a,"<div>&nbsp;</div>"),a=RegExp("<div></div>","gi"),b=b.replace(a,"<div>&nbsp;</div>"),a=RegExp("<div>\\s+</div>","gi"),b=b.replace(a,"<div>&nbsp;</div>"),a=RegExp("<div ([^>]+)><br></div>","gi"),b=b.replace(a,"<div $1>&nbsp;</div>"),a=RegExp("<div ([^>]+)><br/></div>","gi"),b=b.replace(a,"<div $1>&nbsp;</div>"),a=RegExp("<div ([^>]+)><br /></div>","gi"),b=b.replace(a,"<div $1>&nbsp;</div>"),a=RegExp("<div ([^>]+)></div>",
"gi"),b=b.replace(a,"<div $1>&nbsp;</div>"),a=RegExp("<div ([^>]+)>\\s+</div>","gi"),b=b.replace(a,"<div $1>&nbsp;</div>")):(a=RegExp("<div></div>","gi"),b=b.replace(a,"<div><br></div>"),a=RegExp("<div>&nbsp;</div>","gi"),b=b.replace(a,"<div><br></div>"),a=RegExp("<div>\\s+</div>","gi"),b=b.replace(a,"<div><br></div>"),a=RegExp("<div ([^>]+)></div>","gi"),b=b.replace(a,"<div $1><br></div>"),a=RegExp("<div ([^>]+)>&nbsp;</div>","gi"),b=b.replace(a,"<div $1><br></div>"),a=RegExp("<div ([^>]+)>\\s+</div>",
"gi"),b=b.replace(a,"<div $1><br></div>"));if(0==DEXTTOP.DEXT5.browser.ie&&(a=b.match(RegExp("<([^>]*)>","igm"))))for(var d=a.length,h="",f=0;f<d;f++)h=a[f].toString(),h=h.replace(/\r?\n|\r/g,""),b=b.replace(a[f],h);return b},nbspRemove:function(b){if(""==b||void 0==b)return"";var c=null,c=RegExp("<p>&nbsp;</p>","gi");b=b.replace(c,"<p></p>");c=RegExp("<p ([^>]+)>&nbsp;</p>","gi");return b=b.replace(c,"<p $1></p>")},ImageSrcConvert:function(b,c,a){var d=document.createElement("div");d.innerHTML=b;
b=d.getElementsByTagName("img");var h=b.length,f=null,k="",g="";a+="_dext5_base64_image_";for(var e=0;e<h;e++)f=b[e],g=a+e,k=f.src,1==c?-1<k.indexOf("data:image")&&-1<k.indexOf("base64,")&&(this.G_IMG_LIST[g]=k,f.src=g):-1<k.indexOf(a)&&(f.src=this.G_IMG_LIST[g],this.G_IMG_LIST[g]="");return b=d.innerHTML},getUrlString:function(b){b=DEXT5.util.replaceAll(b," ","%20");b=DEXT5.util.replaceAll(b,"&nbsp;","%21");b=DEXT5.util.replaceAll(b,"!","%20");b=DEXT5.util.replaceAll(b,'"',"%22");b=DEXT5.util.replaceAll(b,
"#","%23");b=DEXT5.util.replaceAll(b,"$","%24");b=DEXT5.util.replaceAll(b,"%","%25");b=DEXT5.util.replaceAll(b,"&","%26");b=DEXT5.util.replaceAll(b,"'","%27");b=DEXT5.util.replaceAll(b,"+","%2B");b=DEXT5.util.replaceAll(b,"/","%2F");b=DEXT5.util.replaceAll(b,":","%3A");b=DEXT5.util.replaceAll(b,";","%3B");b=DEXT5.util.replaceAll(b,"<","%3C");b=DEXT5.util.replaceAll(b,"=","%3D");b=DEXT5.util.replaceAll(b,">","%3E");b=DEXT5.util.replaceAll(b,"?","%3F");return b=DEXT5.util.replaceAll(b,"@","%40")},replaceAll:function(b,
c,a){for(var d=b.indexOf(c);-1!=d;)b=b.replace(c,a),d=b.indexOf(c);return b},getSkinNames:function(){return"blue brown darkgray gold gray green orange pink purple red silver yellow".split(" ")},CustomSetting:function(b,c,a){switch(b){case "function":CustomSettingFunction(a);break;case "remove_item":return CustomRemoveItem(c)}},replaceOneSpaceToNbsp:function(b){var c=b,a,d="",h=DEXTTOP.G_CURREDITOR._config.plugInUse;try{var f="span font a b strong i em strike u sup sub".split(" "),k=f.length;if("1"==
h)for(var g=0;g<k;g++)for(var e=0;e<k;e++){d=c;a=new RegExp("<"+f[g]+" *([^>?+])*>(\\s+)</"+f[e]+">","gi");reg_exp2=new RegExp("</"+f[g]+">(\\s+)<"+f[e]+" *([^>?+])*>","gi");try{var r=c.match(a);if(r)for(var n=r.length,p=0;p<n;p++)var m=r[p],t=/>\s+</.exec(m),x=t[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),m=m.replace(t,x),c=c.replace(r[p],m);if(r=c.match(reg_exp2))for(n=r.length,p=0;p<n;p++)m=r[p],t=/>\s+</.exec(m),x=t[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),m=m.replace(t,x),c=c.replace(r[p],
m)}catch(w){c=d}}for(g=0;g<k;g++)for(e=0;e<k;e++)a=new RegExp("/"+f[g]+">\\s<"+f[e],"gi"),c=c.replace(a,"/"+f[g]+">&nbsp;<"+f[e]),a=new RegExp("/"+f[g]+">\\s\\n<"+f[e],"gi"),c=c.replace(a,"/"+f[g]+">&nbsp;<"+f[e]);return c}catch(y){return b}},parseIntOr0:function(b){b=parseInt(b,10);return isNaN(b)?0:b},getUserLang:function(b){b=b.toLowerCase();var c="ko-kr";if(-1<b.indexOf("ko"))c="ko-kr";else if(-1<b.indexOf("en"))c="en-us";else if(-1<b.indexOf("ja"))c="ja-jp";else if(-1<b.indexOf("zh-cn")||0==
b.indexOf("cn"))c="zh-cn";else if(-1<b.indexOf("zh-tw")||0==b.indexOf("tw"))c="zh-tw";return c},base64_decode:function(b){var c="",a,d,h,f,k,g=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<b.length;)a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(g++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(g++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(g++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(g++)),
a=a<<2|d>>4,d=(d&15)<<4|f>>2,h=(f&3)<<6|k,c+=String.fromCharCode(a),64!=f&&(c+=String.fromCharCode(d)),64!=k&&(c+=String.fromCharCode(h));return c=DEXT5.util.utf8_decode(c)},utf8_decode:function(b){for(var c="",a=0,d=c1=c2=0;a<b.length;)d=b.charCodeAt(a),128>d?(c+=String.fromCharCode(d),a++):191<d&&224>d?(c2=b.charCodeAt(a+1),c+=String.fromCharCode((d&31)<<6|c2&63),a+=2):(c2=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),c+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),a+=3);return c},stringToXML:function(b){if(window.ActiveXObject){var c=
new ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(b)}else c=(new DOMParser).parseFromString(b,"text/xml");return c},removeOfficeDummyTag:function(b,c,a){var d=b;try{for(var h=b.indexOf(c),f=b.indexOf(a);-1<h&&-1<f;)var k=d.substring(0,h),g=d.substring(f+a.length),d=k+g,h=d.indexOf(c),f=d.indexOf(a)}catch(e){d=b}return d}};
function DEXT_CONFIG(){""!=DEXT5.config.RootPath&&(DEXT5.rootPath=DEXT5.config.RootPath);this.defaultLineHeight=this.defaultFontFamily=this.defaultFontSize=this.lang=this.dext_path="";this.accessibility="0";this.visibility=!0;this.status_bar=this.top_status_bar=this.tool_bar=this.top_menu="0";this.toSaveFilePathURL=this.toSavePathURL="dext5editordata";this.saveFileFolderNameRule=this.saveFolderNameRule="YYYY/MM";this.serverDomain="";this.saveFileNameRule="GUID";this.showDialogPosition="1";this.image_convert_height=
this.image_convert_width=this.image_convert_format="";this.image_auto_fit="0";this.productKey="";this.imageEditorUse=this.plugInUse="0";this.fileFieldID=this.firstLoadMessage=this.firstLoadType=this.defaultMessage="";this.printPreview="0";this.basePrintFooter=this.basePrintHeader=this.printFooter=this.printHeader="";this.sourceViewtype="0";this.nextTabElementId=this.userCssUrl="";this.xhtml_value=this.empty_tag_remove=this.paste_image_base64="0";this.system_title="DEXT5";this.view_mode_auto_width=
this.view_mode_auto_height="0";this.changeMultiValueMode="doctype";this.tableAutoAdjust="1";this.trustSites="";this.contextMenuDisable="0";this.userFieldValue=this.userFieldID=this.enterTag="";this.mimeCharset="utf-8";this.mimeConentEncodingType="3";this.mimeLocalOnly=this.mimeFileTypeFilter="1";this.mimeRemoveHeader="0";this.imgDefaultVSpace=this.imgDefaultHSpace=this.imgDefaultHeight=this.imgDefaultWidth=this.mimeBaseURL=this.userImageDlgStyle=this.userOpenDlgInitDir=this.userOpenDlgType=this.userOpenDlgTitle=
"";this.officeLineFix="1";this.useLog="0";this.EditorTabDisable="";this.unitDelimiter="\f";this.unitAttributeDelimiter="\x0B";this.style={skinName:"blue",width:"100%",height:"600px",InitVisible:!0,isFontSizeUse:!0,defaultMinHeight:"300px",iconName:"icon"};this.webPath={image:DEXT5.rootPath+"images/editor/",page:DEXT5.rootPath+"pages/",js:DEXT5.rootPath+"js/",js_dev:DEXT5.rootPath+"js_dev/",css:DEXT5.rootPath+"css/",css_dev:DEXT5.rootPath+"css_dev/",include:DEXT5.rootPath+"include/",config:DEXT5.rootPath+
"config/"};this.holderID="";this.config_url=DEXT5.rootPath+"config/dext_editor.xml";this.emoticon_url=DEXT5.rootPath+"config/dext_emoticon.xml";this.forms_url=DEXT5.rootPath+"config/dext_formlist.xml";this.post_url=DEXT5.rootPath+"handler/upload_handler.ashx";this.proxy_url=this.post_url_save_for_notes="";this.plugin_root=DEXT5.rootPath+"plugin/";this.plugin_version=DEXT5.cabVersion;this.editor_url=DEXT5.isRelease?DEXT5.rootPath+"pages/editor_release.html":DEXT5.rootPath+"pages/editor.html";this.pages=
{find:"editor_find.html",replace:"editor_replace.html",image:"editor_image.html",horizontal_line:"editor_horizontal_line.html",bg_image:"dext_bg_image.html",doc_bg_img:"editor_doc_bg_img.html",flash:"editor_flash.html",media:"editor_media.html",table:"editor_table.html",table_property:"editor_table_property.html",cell_property:"editor_cell_property.html",insert_row_column:"editor_insert_row_column.html",row_property:"editor_row_property.html",column_property:"editor_column_property.html",emoticon:"editor_emoticon.html",
bookmark:"editor_bookmark.html",iframe:"editor_iframe.html",hyperlink:"editor_hyperlink.html",split_cell:"editor_split_cell.html",about:"editor_about.html",symbol:"editor_symbol.html",setting:"editor_setting.html",template:"editor_template.html",tool_replace:"editor_tool_replace.html",insert_link_media:"editor_insert_link_media.html",m_image:"editor_m_image.html",m_emoticon:"editor_m_emoticon.html",cell_border:"editor_cell_border.html",paste_dialog:"editor_paste.html",shortcut:"editor_shortcut.html",
layout:"editor_layout.html",insert_file:"editor_insert_file.html",file_open:"editor_file_open.html",blockquote:"editor_blockquote.html",input_text:"editor_input_text.html",input_radio:"editor_input_radio.html",input_checkbox:"editor_input_checkbox.html",input_button:"editor_input_button.html",input_hidden:"editor_input_hidden.html",input_textarea:"editor_input_textarea.html",input_select:"editor_input_select.html",input_image:"editor_input_image.html",accessibility_validation:"editor_accessibility_validation.html",
code_snippet:"editor_code_snippet.html"};this.editor_id=this.xss_use=this.xss_remove_events=this.xss_remove_tags=this.replace_tagname="";this.mode="edit";this.mimeUse="0";this.zIndex=1E4;this.ruler={use:"0",view:"0",rulerInitPosition:"0",viewPointer:"1",viewGuideLine:"1",viewRuler:"1"};this.horizontalLine={use:"0",url:""};this.editorborder="1";this.imageBaseUrl=this.custom_code="";this.allowMediaFileType=[];this.allowImageFileType=[];this.allowFlashFileType=[];this.allowInsertFileType=[];this.attachFileImage=
"1";this.tableClassList=[];this.tableLineStyleList=[];this.tableDefaultTdHeight=this.tableDefaultClass=this.tableDefaultHeight=this.tableDefaultWidth="";this.tableLineStyleValue={};this.tableLineStyleValue._solid="border-top: 1px solid #5d5d5d;";this.tableLineStyleValue._dotted="border-top: 1px dotted #5d5d5d;";this.tableLineStyleValue._dashed="border-top: 1px dashed #5d5d5d;";this.tableLineStyleValue._double="border-top: 3px double #5d5d5d;";this.tableLineStyleValue._groove="border: 3px groove #e1e1e1;";
this.tableLineStyleValue._ridge="border: 3px ridge #e1e1e1;";this.tableLineStyleValue._inset="border: 3px inset #e1e1e1;";this.tableLineStyleValue._outset="border: 3px outset #e1e1e1;";this.tableLineStyleValue._none="border: 1px none #5d5d5d;";this.tableLineStyleValue._hidden="border: 1px none #5d5d5d;";this.tableDefaultInoutdent=20;this.tableNoSelectionClass=this.tableNoActionClass=this.tableNoResizeClass=this.tableInitInoutdent="";this.tableColMaxCount=this.tableRowMaxCount="13";this.showLineForBorderNone=
this.allowInoutdentText="0";this.tabIndexObjId=this.focusInitEditorObjId=this.focusInitObjId="";this.setDefaultStyle={value:"0",body_id:"dext_body"};this.setDefaultUserStyle=[];this.popupCssUrl="../css/editor_popup.css";this.symbolUrl="../js/editor_symbol.js";this.dialogJSUrl="../js/editor_dialog.js";this.customEventCmd={image:{ondbclick:""}};this.ieCompatible="";this.autoUrlDetect="1";this.scrollOverflow=this.pasteRemoveEmptyTag="0";this.disableKeydown=this.autoBodyFit=this.disableTabletap=this.defaultImemode=
"";this.dragAndDropAllow="0";this.limitPasteHtmlLength={value:"0",length:13E5};this.pasteToImage="1";this.eventForPasteImage=this.notRepairInViewMode=this.viewModeAllowCopy=this.viewModeBrowserMenu=this.removeSpaceInTagname=this.wrapPtagToSource="0";this.useHtmlCorrection=this.removeColgroup="1";this.runtimes="";this.setAutoSave={mode:"2",interval:.5};this.insertCarriageReturn="0";this.returnEvent={mouse_event:"0",key_event:"0"};this.useCorrectInOutdent="0";this.isLoadedEditor=!1;this.setValueObjId=
"";this.replaceEmptyTagWithSpace="1";this.LoadedEvent="";this.frameFullScreen="0";this.currFontFamily="";this.allowImgSize="1";this.hyperlinkTargetList=[];this.hyperlinkCategoryList=[];this.developLang="NET";this.formMode="0";this.tableLock={use:"0",showLockIconUserMode:"0",lockName:["dext_lock"],tableLockMode:"2"};this.openDocument={word:{maxSize:0,maxPage:0},excel:{maxSize:0,maxSheet:0},powerpoint:{maxSize:0,maxSlide:0}};this.removeLastBrTag="0";this.editorBodyEditable=!0;this.inoutdentDefaultSize=
40;this.statusBarItem=this.accessibilityValidationItems="";this.statusBarInitMode="design";this.dragResize="0";this.dragResizeApplyBrowser=[];this.replaceOutsideImage={use:"0",exceptDomain:[]};this.bodyOutsideCodeCut="0";this.eventList=[];this.userJsUrl="";this.fontFamilyList=[];this.fontSizeList=[];this.lineHeightList=[];this.formattingList=[]}
function isExistEditorName(b){if(void 0==b||""==b)return 1;var c=DEXT5.DEXTMULTIPLE["dext_frame_"+b];return void 0==c||null==c?0:""!=DEXT5.config.EditorHolder&&DEXT5.DEXTHOLDER[b]==DEXT5.config.EditorHolder?3:2}function getNewNextEditorName(b){var c="",c=b.split("_"),a=c.length;1<a&&(b=b.replace("_"+c[a-1],""));c=b+getNextEditorNumber();0<isExistEditorName(c)&&(c=getNewNextEditorName(c));return c}var getNextEditorNumber=function(){var b=0;return function(){return"_"+ ++b}}();
function Dext5editor(b){var c=isExistEditorName(b);if(1==c)alert("editor's name is empty. Please, check editor's name");else{if(2==c)if("1"==DEXT5.config.IgnoreSameEditorName)b=getNewNextEditorName(b);else{alert("editor's name is already exist. Please, check editor's name");return}var a=new DEXT_CONFIG;if(0<DEXT5.config.InitServerXml.length)if(-1<DEXT5.config.InitServerXml.indexOf("f="))a.config_url=DEXT5.config.InitServerXml+"&dext5CMD=configRequest";else{alert("Error occurred reading the Editor Settings");
return}else 0<DEXT5.config.InitXml.length&&(0==DEXT5.config.InitXml.indexOf("http")?a.config_url=DEXT5.config.InitXml:a.config_url=DEXT5.rootPath+"config/"+DEXT5.config.InitXml);-1<a.config_url.indexOf("?")?a.config_url+="&t="+(new Date).getTime():a.config_url+="?t="+(new Date).getTime();var d=null,d=0<DEXT5.config.InitServerXml.length?DEXT5.ajax.load(a.config_url):DEXT5.ajax.loadXml(a.config_url);if(null==d)alert("ErrCode : 1000");else{if("object"!=typeof d)if(0==d.indexOf("[OK]"))d=d.substring(4),
d=DEXT5.util.base64_decode(d),d=d.substring(d.indexOf("<?")),d=DEXT5.util.stringToXML(d);else if(0==d.indexOf("[FAIL]")){alert("Error occurred reading the Editor Settings");return}this.configXml=d;3!=c&&(DEXT5.DEXTMULTIPLE["dext_frame_"+b]=b,DEXT5.DEXTHOLDER[b]=DEXT5.config.EditorHolder);DEXT5.isRelease?(a.popupCssUrl="../css/editor_popup.css",a.dialogJSUrl="../js/editor_dialog.js"):(a.popupCssUrl="../css_dev/editor_popup.css",a.dialogJSUrl="../js_dev/editor_dialog.js");var h=DEXT5.util.xml.getNode(d,
"xss_protection"),f=DEXT5.util.xml.getNodeValue(h,"xss_use"),k=DEXT5.util.xml.getNodeValue(h,"xss_remove_tags"),g=DEXT5.util.xml.getNodeValue(h,"xss_remove_events");""==f&&(f="0");""!=DEXT5.config.zXssUse&&(f=DEXT5.config.zXssUse);a.xss_use=f;""!=DEXT5.config.zXssRemoveTags&&(k=DEXT5.config.zXssRemoveTags);a.xss_remove_tags=k.toLowerCase();""!=DEXT5.config.zXssRemoveEvents&&(g=DEXT5.config.zXssRemoveEvents);"all"==g.toLowerCase()?a.xss_remove_events="onabort,onactivate,onafterprint,onafterupdate,onbeforeactivate,onbeforecopy,onbeforecut,onbeforedeactivate,onbeforeeditfocus,onbeforepaste,onbeforeprint,onbeforeunload,onbeforeupdate,onbegin,onblur,onbounce,oncellchange,onchange,onclick,oncontentready,oncontentsave,oncontextmenu,oncontrolselect,oncopy,oncut,ondataavailable, ondatasetchanged, ondatasetcomplete, ondblclick, ondeactivate,ondetach, ondocumentready, ondrag, ondragdrop, ondragend,ondragenter,ondragleave,ondragover,ondragstart,ondrop,onend,onerror,onerrorupdate,onfilterchange,onfinish,onfocus,onfocusin,onfocusout,onhelp,onhide,onkeydown,onkeypress,onkeyup,onlayoutcomplete,onload,onlosecapture,onmediacomplete,onmediaerror,onmedialoadfailed,onmousedown,onmouseenter,onmouseleave,onmousemove,onmouseout,onmouseover,onmouseup,onmousewheel,onmove,onmoveend,onmovestart,onopenstatechange,onoutofsync,onpaste,onpause,onplaystatechange,onpropertychange,onreadystatechange,onrepeat,onreset,onresize,onresizeend,onresizestart,onresume,onreverse,onrowclick,onrowenter,onrowexit,onrowout,onrowover,onrowsdelete,onrowsinserted,onsave,onscroll,onseek,onselect,onselectionchange,onselectstart,onshow,onstart,onstop,onsubmit,onsyncrestored,ontimeerror,ontrackchange,onunload,onurlflip":
a.xss_remove_events=g.toLowerCase();1E4<=parseInt(DEXT5.config.zIndex,10)&&(a.zIndex=parseInt(DEXT5.config.zIndex,10));a.editorborder=""==DEXT5.config.EditorBorder?"1":DEXT5.config.EditorBorder;var e=DEXT5.util.xml.getNode(d,"setting"),r=DEXT5.util.xml.getNodeValue(e,"runtimes"),n=DEXT5.util.xml.getNodeValue(e,"width"),p=DEXT5.util.xml.getNodeValue(e,"height"),m=DEXT5.util.xml.getNodeValue(e,"skinname"),t=DEXT5.util.xml.getNodeValue(e,"lang"),x=DEXT5.util.xml.getNodeValue(e,"accessibility"),w=DEXT5.util.xml.getNodeValue(e,
"showdialog_pos"),y=DEXT5.util.xml.getNodeValue(e,"source_viewtype"),F=DEXT5.util.xml.getNodeValue(e,"user_css_url"),Y=DEXT5.util.xml.getNodeValue(e,"xhtml_value"),G=DEXT5.util.xml.getNodeValue(e,"system_title"),da=DEXT5.util.xml.getNodeValue(e,"table_auto_adjust"),ta=DEXT5.util.xml.getNodeValue(e,"context_menu_disable"),Q=DEXT5.util.xml.getNodeValue(e,"enter_tag"),ua=DEXT5.util.xml.getNodeValue(e,"office_linefix"),va=DEXT5.util.xml.getNodeValue(e,"editor_tab_disable"),wa=DEXT5.util.xml.getNodeValue(e,
"frame_fullscreen");"0"==DEXT5.util.xml.getNodeValue(e,"allow_img_size")&&(a.allowImgSize="0");""!=DEXT5.config.FrameFullScreen?a.frameFullScreen=DEXT5.config.FrameFullScreen:""!=wa&&(a.frameFullScreen=wa);var ea="";""!=DEXT5.config.RunTimes?ea=DEXT5.config.RunTimes:""!=r&&(ea=r);a.runtimes=GetUserRunTimeEditor(ea);a.EditorTabDisable=""==DEXT5.config.EditorTabDisable?0==va.length?a.EditorTabDisable:va:DEXT5.config.EditorTabDisable;a.contextMenuDisable="1"==ta?"1":"0";var xa=DEXT5.util.xml.getNodeValue(e,
"ie_compatible");""!=xa&&(a.ieCompatible=xa);var ya=DEXT5.util.xml.getNodeValue(e,"auto_url_detect");""!=ya&&(a.autoUrlDetect=ya);a.officeLineFix=""==DEXT5.config.officeLineFix?0==ua.length?a.officeLineFix:ua:DEXT5.config.officeLineFix;"1"==DEXT5.util.xml.getNodeValue(e,"paste_remove_empty_tag")&&(a.pasteRemoveEmptyTag="1");var za=DEXT5.util.xml.getNodeValue(e,"scroll_overflow");a.scrollOverflow=""==DEXT5.config.scrollOverflow?0==za.length?a.scrollOverflow:za:DEXT5.config.scrollOverflow;"1"==DEXT5.util.xml.getNodeValue(e,
"default_imemode")&&(a.defaultImemode="1");"1"==DEXT5.util.xml.getNodeValue(e,"disable_tabletap")&&(a.disableTabletap="1");"1"==DEXT5.util.xml.getNodeValue(e,"auto_body_fit")&&(a.autoBodyFit="1");"1"==DEXT5.util.xml.getNodeValue(e,"disable_keydown")&&(a.disableKeydown="1");var vb=DEXT5.util.xml.getNode(e,"custom_event"),wb=DEXT5.util.xml.getNode(vb,"image"),Aa=DEXT5.util.xml.getNodeValue(wb,"ondbclick");""!=Aa&&(a.customEventCmd.image.ondbclick=Aa);var xb=DEXT5.util.xml.getNode(e,"pageurl"),yb=DEXT5.util.xml.getNode(xb,
"script"),Ba=DEXT5.util.xml.getNodeValue(yb,"symbol");a.symbolUrl=""==DEXT5.config.SymbolUrl?""!=Ba?Ba:DEXT5.isRelease?"../js/editor_symbol.js":"../js_dev/editor_symbol.js":DEXT5.config.SymbolUrl;var fa=DEXT5.util.xml.getNodeValue(e,"icon_name");""!=fa&&(a.style.iconName=fa,DEXT5.config.IconName=fa);if(""==DEXT5.config.ImageBaseUrl){var Ca=DEXT5.util.xml.getNodeValue(e,"image_base_url");""!=Ca&&(a.imageBaseUrl=Ca)}else a.imageBaseUrl=DEXT5.config.ImageBaseUrl;if(""==DEXT5.config.DragResize){var Da=
DEXT5.util.xml.getNodeValue(e,"drag_resize");""!=Da&&(a.dragResize=Da)}else a.dragResize=DEXT5.config.DragResize;if(""==DEXT5.config.DragResizeApplyBrowser){var Z=DEXT5.util.xml.getNode(e,"drag_resize");Z&&Z.getAttribute("apply_browser")&&""!=Z.getAttribute("apply_browser")&&(a.dragResizeApplyBrowser=Z.getAttribute("apply_browser").split(","))}else a.dragResizeApplyBrowser=DEXT5.config.DragResizeApplyBrowser.split(",");""!=DEXT5.config.FontFamilyList&&(a.fontFamilyList=DEXT5.config.FontFamilyList.split(","));
""!=DEXT5.config.FontSizeList&&(a.fontSizeList=a.fontSizeList.concat(DEXT5.config.FontSizeList.split(",")));""!=DEXT5.config.LineHeightList&&(a.lineHeightList.push(""),a.lineHeightList=a.lineHeightList.concat(DEXT5.config.LineHeightList.split(",")));""!=DEXT5.config.FormattingList&&(a.formattingList.push(""),a.formattingList=a.formattingList.concat(DEXT5.config.FormattingList.split(",")));if("1"==DEXT5.util.xml.getNodeValue(e,"use_ruler")){a.ruler.use="1";a.ruler.view="1";var E=DEXT5.util.xml.getNode(e,
"use_ruler");E.getAttribute("ruler_init_position")&&""!=E.getAttribute("ruler_init_position")&&(a.ruler.rulerInitPosition=E.getAttribute("ruler_init_position"));E.getAttribute("view_pointer")&&"1"!=E.getAttribute("view_pointer")&&(a.ruler.viewPointer="0");E.getAttribute("view_guide_line")&&"1"!=E.getAttribute("view_guide_line")&&(a.ruler.viewGuideLine="0");E.getAttribute("view_ruler")&&"1"!=E.getAttribute("view_ruler")&&(a.ruler.viewRuler="0")}if("1"==DEXT5.util.xml.getNodeValue(e,"use_horizontal_line")){var ga=
DEXT5.util.xml.getNode(e,"use_horizontal_line");ga.getAttribute("url")&&""!=ga.getAttribute("url")&&(a.horizontalLine.use="1",a.horizontalLine.url=ga.getAttribute("url"))}if(""==a.enterTag){if(Q=Q.toLocaleLowerCase(),"br"==Q||"div"==Q)a.enterTag=Q}else a.enterTag=a.enterTag.toLocaleLowerCase(),a.enterTag="br"!=a.enterTag&&"div"!=a.enterTag?"":Q;var ha=DEXT5.util.xml.getNodeValue(e,"set_default_style");if(""!=ha&&"0"!=ha){a.setDefaultStyle.value=ha;var T=DEXT5.util.xml.getNode(e,"set_default_style");
""!=T.getAttribute("body_id")&&(a.setDefaultStyle.body_id=T.getAttribute("body_id"));T.getAttribute("user_style")&&""!=T.getAttribute("user_style")&&(a.setDefaultUserStyle=T.getAttribute("user_style").split(","))}var Ea=DEXT5.util.xml.getNodeValue(e,"drag_and_drop_allow");"1"==Ea&&(a.dragAndDropAllow=Ea);if("1"==DEXT5.util.xml.getNodeValue(e,"limit_paste_html_length")){a.limitPasteHtmlLength.value="1";var Fa=DEXT5.util.xml.getNode(e,"limit_paste_html_length");""!=Fa.getAttribute("length")&&(a.limitPasteHtmlLength.length=
parseInt(Fa.getAttribute("length"),10))}"1"==DEXT5.util.xml.getNodeValue(e,"wrap_ptag_to_source")&&(a.wrapPtagToSource="1");var ia=DEXT5.util.xml.getNodeValue(e,"paste_to_image");if("0"==ia||"2"==ia)a.pasteToImage=ia;"1"==DEXT5.util.xml.getNodeValue(e,"remove_space_in_tagname")&&(a.removeSpaceInTagname="1");"1"==DEXT5.util.xml.getNodeValue(e,"view_mode_browser_menu")&&(a.viewModeBrowserMenu="1");"1"==DEXT5.util.xml.getNodeValue(e,"view_mode_allow_copy")&&(a.viewModeAllowCopy="1");"1"==DEXT5.util.xml.getNodeValue(e,
"event_for_paste_image")&&(a.eventForPasteImage="1");"0"==DEXT5.util.xml.getNodeValue(e,"remove_colgroup")&&(a.removeColgroup="0");"0"==DEXT5.util.xml.getNodeValue(e,"use_html_correction")&&(a.useHtmlCorrection="0");var Ga=DEXT5.util.xml.getNodeValue(e,"formlist_url");""!=DEXT5.config.FormListUrl?a.forms_url=DEXT5.config.FormListUrl:""!=Ga&&(a.forms_url=Ga);var ja=DEXT5.util.xml.getNodeValue(e,"set_auto_save");if(""!=ja&&(a.setAutoSave.mode=ja,"1"==ja&&(xmlSetAutoSaveNode=DEXT5.util.xml.getNode(e,
"set_auto_save"),xmlSetAutoSaveNode.getAttribute("interval")&&""!=xmlSetAutoSaveNode.getAttribute("interval")))){var ka;ka=Math.floor(10*xmlSetAutoSaveNode.getAttribute("interval"))/10;.5<=ka&&(a.setAutoSave.interval=ka)}"1"==DEXT5.util.xml.getNodeValue(e,"insert_carriage_return")&&(a.insertCarriageReturn="1");var U=DEXT5.util.xml.getNode(e,"return_event");U&&(U.getAttribute("mouse_event")&&"1"==U.getAttribute("mouse_event")&&(a.returnEvent.mouse_event="1"),U.getAttribute("keyboard_event")&&"1"==
U.getAttribute("keyboard_event")&&(a.returnEvent.key_event="1"));"1"==DEXT5.util.xml.getNodeValue(e,"use_correct_in_outdent")&&(a.useCorrectInOutdent="1");"0"==DEXT5.util.xml.getNodeValue(e,"replace_empty_tag_with_space")&&(a.replaceEmptyTagWithSpace="0");var B=DEXT5.util.xml.getNode(e,"form_mode");""!=DEXT5.config.FormMode?a.formMode=DEXT5.config.FormMode:B&&B.getAttribute("use")&&"1"==B.getAttribute("use")&&(a.formMode=B.getAttribute("use"));"1"==a.formMode&&"1"==DEXT5.config.BodyOutsideCodeCut?
a.bodyOutsideCodeCut="1":B&&"1"==a.formMode&&"1"==DEXT5.util.xml.getNodeValue(B,"body_outside_code_cut")&&(a.bodyOutsideCodeCut="1");if("1"==a.formMode&&""!=DEXT5.config.EventList)a.eventList=DEXT5.config.EventList.split(",");else if(B&&"1"==a.formMode)for(var Ha=DEXT5.util.xml.getNode(B,"event_list"),zb=DEXT5.util.xml.count(Ha,"event"),l=0;l<zb;l++)a.eventList[l]=DEXT5.util.xml.getNodeValueIdx(Ha,"event",l);if(""!=DEXT5.config.TableLock.Use)a.tableLock.use=DEXT5.config.TableLock.Use,""!=DEXT5.config.TableLock.LockName&&
(a.tableLock.lockName=DEXT5.config.TableLock.LockName.split(",")),""!=DEXT5.config.TableLock.ShowLockIconUserMode&&(a.tableLock.showLockIconUserMode=DEXT5.config.TableLock.ShowLockIconUserMode),""!=DEXT5.config.TableLock.TableLockMode&&(a.tableLock.tableLockMode=DEXT5.config.TableLock.TableLockMode);else if(B&&"1"==DEXT5.util.xml.getNodeValue(B,"table_lock")){a.tableLock.use="1";var z=DEXT5.util.xml.getNode(B,"table_lock");z&&z.getAttribute("lock_name")&&""!=z.getAttribute("lock_name")&&(a.tableLock.lockName=
z.getAttribute("lock_name").split(","));z&&z.getAttribute("show_lock_icon_user_mode")&&""!=z.getAttribute("show_lock_icon_user_mode")&&(a.tableLock.showLockIconUserMode=z.getAttribute("show_lock_icon_user_mode"));z&&z.getAttribute("table_lock_mode")&&""!=z.getAttribute("table_lock_mode")&&(a.tableLock.tableLockMode=z.getAttribute("table_lock_mode"))}var la=DEXT5.util.xml.getNodeValue(e,"user_js_url");5<la.length&&"http"==la.substring(0,4).toLowerCase()?a.userJsUrl=la:a.userJsUrl="";var aa=DEXT5.util.xml.getNode(e,
"open_document");if(aa){var N=DEXT5.util.xml.getNode(aa,"word");N&&(N.getAttribute("max_size")&&""!=N.getAttribute("max_size")&&(a.openDocument.word.maxSize=parseInt(N.getAttribute("max_size"),0)),N.getAttribute("max_page")&&""!=N.getAttribute("max_page")&&(a.openDocument.word.maxPage=parseInt(N.getAttribute("max_page"),0)));var O=DEXT5.util.xml.getNode(aa,"excel");O&&(O.getAttribute("max_size")&&""!=O.getAttribute("max_size")&&(a.openDocument.excel.maxSize=parseInt(O.getAttribute("max_size"),0)),
O.getAttribute("max_sheet")&&""!=O.getAttribute("max_sheet")&&(a.openDocument.excel.maxSheet=parseInt(O.getAttribute("max_sheet"),0)));var P=DEXT5.util.xml.getNode(aa,"powerpoint");P&&(P.getAttribute("max_size")&&""!=P.getAttribute("max_size")&&(a.openDocument.powerpoint.maxSize=parseInt(P.getAttribute("max_size"),0)),P.getAttribute("max_slide")&&""!=P.getAttribute("max_slide")&&(a.openDocument.powerpoint.maxSlide=parseInt(P.getAttribute("max_slide"),0)))}"1"==DEXT5.util.xml.getNodeValue(e,"remove_last_br_tag")&&
(a.removeLastBrTag="1");""!=DEXT5.config.EditorBodyEditable?"0"==DEXT5.config.EditorBodyEditable&&(a.editorBodyEditable=!1):"0"==DEXT5.util.xml.getNodeValue(e,"editor_body_editable")&&(a.editorBodyEditable=!1);if(""!=DEXT5.config.ReplaceOutsideImage)a.replaceOutsideImage.use=DEXT5.config.ReplaceOutsideImage,""!=DEXT5.config.ReplaceOutsideImageExceptDomain&&(a.replaceOutsideImage.exceptDomain=DEXT5.config.ReplaceOutsideImageExceptDomain.split(","));else if("1"==DEXT5.util.xml.getNodeValue(e,"replace_outside_image")){a.replaceOutsideImage.use=
"1";var ma=DEXT5.util.xml.getNode(e,"replace_outside_image");ma.getAttribute("except_domain")&&""!=ma.getAttribute("except_domain")&&(a.replaceOutsideImage.exceptDomain=ma.getAttribute("except_domain").split(","))}var u=DEXT5.util.xml.getNode(d,"uploader_setting"),H=DEXT5.util.xml.getNodeValue(u,"develop_langage"),D=DEXT5.util.xml.getNodeValue(u,"handler_url"),Ia=DEXT5.util.xml.getNodeValue(u,"to_save_path_url"),Ja=DEXT5.util.xml.getNodeValue(u,"to_save_file_path_url"),I=DEXT5.util.xml.getNodeValue(u,
"save_foldername_rule"),J=DEXT5.util.xml.getNodeValue(u,"save_file_foldername_rule"),Ab=DEXT5.util.xml.getNodeValue(u,"server_domain"),na=DEXT5.util.xml.getNodeValue(u,"save_filename_rule"),Bb=DEXT5.util.xml.getNodeValue(u,"image_convert_format"),Cb=DEXT5.util.xml.getNodeValue(u,"image_convert_width"),Db=DEXT5.util.xml.getNodeValue(u,"image_convert_height"),Eb=DEXT5.util.xml.getNodeValue(u,"image_auto_fit"),Ka=DEXT5.util.xml.getNodeValue(u,"handler_url_save_for_notes");""!=Ka&&(a.post_url_save_for_notes=
Ka);var ba=DEXT5.util.xml.getNode(d,"extra_setting");ba&&(a.paste_image_base64=DEXT5.util.xml.getNodeValue(ba,"paste_image_base64"),a.empty_tag_remove=DEXT5.util.xml.getNodeValue(ba,"empty_tag_remove"),a.custom_code=DEXT5.util.xml.getNodeValue(ba,"custom_code"),DEXT5.config.CustomCode=a.custom_code);a.serverDomain=Ab;0<DEXT5.config.ServerDomain.length&&(a.serverDomain=DEXT5.config.ServerDomain);0<DEXT5.config.HandlerUrl.length&&(D=DEXT5.config.HandlerUrl);a.image_convert_format=Bb;a.image_convert_width=
Cb;a.image_convert_height=Db;a.image_auto_fit=Eb;var La=DEXT5.util.xml.getNodeValue(u,"allow_media_file_type");if(0<La.length)for(var Ma=La.split(","),Fb=Ma.length,l=0;l<Fb;l++)a.allowMediaFileType.push(Ma[l]);else a.allowMediaFileType=["wmv","asf"];var Na=DEXT5.util.xml.getNodeValue(u,"allow_image_file_type");if(0<Na.length)for(var Oa=Na.split(","),Gb=Oa.length,l=0;l<Gb;l++)a.allowImageFileType.push(Oa[l]);else a.allowImageFileType=["jpg","jpeg","png","gif","bmp"];var Pa=DEXT5.util.xml.getNodeValue(u,
"allow_flash_file_type");if(0<Pa.length)for(var Qa=Pa.split(","),Hb=Qa.length,l=0;l<Hb;l++)a.allowFlashFileType.push(Qa[l]);else a.allowFlashFileType=["swf"];var Ra=DEXT5.util.xml.getNodeValue(u,"allow_insert_file_type");if(0<Ra.length)for(var Sa=Ra.split(","),Ib=Sa.length,l=0;l<Ib;l++)a.allowInsertFileType.push(Sa[l]);else a.allowInsertFileType="txt doc docx xls xlsx ppt pptx hwp pdf".split(" ");"0"==DEXT5.util.xml.getNodeValue(u,"attach_file_image")&&(a.attachFileImage="0");var K=DEXT5.util.xml.getNode(e,
"file_delimiter");""!=DEXT5.config.UnitDelimiter?a.unitDelimiter=String.fromCharCode(DEXT5.config.UnitDelimiter):K&&K.getAttribute("unit_delimiter")&&""!=K.getAttribute("unit_delimiter")&&(a.unitDelimiter=String.fromCharCode(K.getAttribute("unit_delimiter")));""!=DEXT5.config.UnitDelimiter?a.unitAttributeDelimiter=String.fromCharCode(DEXT5.config.UnitAttributeDelimiter):K&&K.getAttribute("unit_attribute_delimiter")&&""!=K.getAttribute("unit_attribute_delimiter")&&(a.unitAttributeDelimiter=String.fromCharCode(K.getAttribute("unit_attribute_delimiter")));
var oa=DEXT5.util.xml.getNode(e,"inoutdent");oa&&oa.getAttribute("default_size")&&(a.inoutdentDefaultSize=oa.getAttribute("default_size"));var q=DEXT5.util.xml.getNode(e,"table_property");q&&(q.getAttribute("width")&&(a.tableDefaultWidth=q.getAttribute("width")),q.getAttribute("height")&&(a.tableDefaultHeight=q.getAttribute("height")),q.getAttribute("class")&&(a.tableDefaultClass=q.getAttribute("class")),q.getAttribute("inoutdent")&&(a.tableDefaultInoutdent=q.getAttribute("inoutdent")),q.getAttribute("init_inoutdent")&&
(a.tableInitInoutdent=q.getAttribute("init_inoutdent")),q.getAttribute("td_height")&&(a.tableDefaultTdHeight=q.getAttribute("td_height")),q.getAttribute("row_max_count")&&(a.tableRowMaxCount=q.getAttribute("row_max_count")),q.getAttribute("col_max_count")&&(a.tableColMaxCount=q.getAttribute("col_max_count")),q.getAttribute("allow_inoutdent_text")&&(a.allowInoutdentText=q.getAttribute("allow_inoutdent_text")));var Ta=DEXT5.util.xml.getNodeValue(q,"class_list");if(0<Ta.length)for(var Ua=Ta.split(","),
Jb=Ua.length,l=0;l<Jb;l++)a.tableClassList.push(Ua[l]);var Va=DEXT5.util.xml.getNodeValue(q,"show_line_for_border_none");"0"!=Va&&(a.showLineForBorderNone=Va);var Wa=DEXT5.util.xml.getNodeValue(q,"line_style");if(0<Wa.length)for(var Xa=Wa.split(","),Kb=Xa.length,l=0;l<Kb;l++)a.tableLineStyleList.push(Xa[l]);var Ya=DEXT5.util.xml.getNode(e,"hyperlink_property"),Za=DEXT5.util.xml.getNodeValue(Ya,"target");if(0<Za.length)for(var $a=Za.split(","),Lb=$a.length,l=0;l<Lb;l++)a.hyperlinkTargetList.push($a[l]);
var ab=DEXT5.util.xml.getNodeValue(Ya,"category");if(0<ab.length)for(var bb=ab.split(","),Mb=bb.length,l=0;l<Mb;l++)a.hyperlinkCategoryList.push(bb[l]);var cb=DEXT5.util.xml.getNodeValue(q,"no_resize_class");0<cb.length&&(a.tableNoResizeClass=cb);var db=DEXT5.util.xml.getNodeValue(q,"no_selection_class");0<db.length&&(a.tableNoSelectionClass=db);var eb=DEXT5.util.xml.getNodeValue(q,"no_action_class");0<eb.length&&(a.tableNoActionClass=eb);var R=DEXT5.util.xml.getNode(e,"img_default_size");R&&R.getAttribute("width")&&
(a.imgDefaultWidth=R.getAttribute("width"));R&&R.getAttribute("height")&&(a.imgDefaultHeight=R.getAttribute("height"));var S=DEXT5.util.xml.getNode(e,"img_default_space");S&&S.getAttribute("hspace")&&(a.imgDefaultHSpace=S.getAttribute("hspace"));S&&S.getAttribute("vspace")&&(a.imgDefaultVSpace=S.getAttribute("vspace"));a.style.width=""==DEXT5.config.Width?0==n.length?a.style.width:n:DEXT5.config.Width;a.style.height=""==DEXT5.config.Height?0==p.length?a.style.height:p:DEXT5.config.Height;a.style.skinName=
""==DEXT5.config.SkinName?0==m.length?a.style.skinName:m:DEXT5.config.SkinName;if("random"==a.style.skinName){var Nb=Math.floor(11*Math.random()),Ob=DEXT5.util.getSkinNames();a.style.skinName=Ob[Nb]}a.defaultMessage=""==DEXT5.config.DefaultMessage?"":DEXT5.config.DefaultMessage;a.firstLoadType=""==DEXT5.config.FirstLoadType?"":DEXT5.config.FirstLoadType;a.firstLoadMessage=""==DEXT5.config.FirstLoadMessage?"":DEXT5.config.FirstLoadMessage;a.fileFieldID=""==DEXT5.config.FileFieldID?"Filedata":DEXT5.config.FileFieldID;
a.nextTabElementId=""==DEXT5.config.NextTabElementId?"":DEXT5.config.NextTabElementId;a.userFieldID=""==DEXT5.config.UserFieldID?"Userdata":DEXT5.config.UserFieldID;a.userFieldValue=DEXT5.config.UserFieldValue;a.toSavePathURL=""==DEXT5.config.ToSavePathURL?0==Ia.length?a.toSavePathURL:Ia:DEXT5.config.ToSavePathURL;a.toSaveFilePathURL=""==DEXT5.config.ToSaveFilePathURL?0==Ja.length?a.toSaveFilePathURL:Ja:DEXT5.config.ToSaveFilePathURL;a.sourceViewtype="1"==y||"2"==y?y:"0";5<F.length&&"http"==F.substring(0,
4).toLowerCase()?a.userCssUrl=F:a.userCssUrl="";a.xhtml_value="1"==Y?"1":"0";""!=G&&(a.system_title="0"==G?"":G);if(""!=DEXT5.config.ViewModeAutoHeight)a.view_mode_auto_height=DEXT5.config.ViewModeAutoHeight;else{var fb=DEXT5.util.xml.getNodeValue(e,"view_mode_auto_height");""!=fb&&(a.view_mode_auto_height=fb)}if(""!=DEXT5.config.ViewModeAutoWidth)a.view_mode_auto_width=DEXT5.config.ViewModeAutoWidth;else{var gb=DEXT5.util.xml.getNodeValue(e,"view_mode_auto_width");""!=gb&&(a.view_mode_auto_width=
gb)}""!=DEXT5.config.ChangeMultiValueMode&&(a.changeMultiValueMode=DEXT5.config.ChangeMultiValueMode);"0"==da&&(a.tableAutoAdjust="0");0<DEXT5.config.mimeCharset.length&&(a.mimeCharset=DEXT5.config.mimeCharset);0<DEXT5.config.mimeConentEncodingType.length&&(a.mimeConentEncodingType=DEXT5.config.mimeConentEncodingType);0<DEXT5.config.mimeLocalOnly.length&&(a.mimeLocalOnly=DEXT5.config.mimeLocalOnly);0<DEXT5.config.mimeRemoveHeader.length&&(a.mimeRemoveHeader=DEXT5.config.mimeRemoveHeader);0<DEXT5.config.mimeFileTypeFilter.length&&
(a.mimeFileTypeFilter=DEXT5.config.mimeFileTypeFilter);0<DEXT5.config.userOpenDlgTitle.length&&(a.userOpenDlgTitle=DEXT5.config.userOpenDlgTitle);0<DEXT5.config.userOpenDlgType.length&&(a.userOpenDlgType=DEXT5.config.userOpenDlgType);0<DEXT5.config.userOpenDlgInitDir.length&&(a.userOpenDlgInitDir=DEXT5.config.userOpenDlgInitDir);0<DEXT5.config.userImageDlgStyle.length&&(a.userImageDlgStyle=DEXT5.config.userImageDlgStyle);0<DEXT5.config.mimeBaseURL.length&&(a.mimeBaseURL=DEXT5.config.mimeBaseURL);
""!=DEXT5.config.ShowDialogPosition?a.showDialogPosition=DEXT5.config.ShowDialogPosition:""!=w&&(a.showDialogPosition=w);""!=DEXT5.config.StatusBarItem&&(a.statusBarItem=DEXT5.config.StatusBarItem);t=t.toLowerCase();a.lang=""==t?"ko-kr":DEXT5.util.getUserLang(t);2<=DEXT5.config.InitLang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.InitLang));2<=DEXT5.config.Lang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.Lang));a.accessibility=0==x.length?"0":x;var pa=DEXT5.util.xml.getNode(e,"accessibility");
""==DEXT5.config.AccessibilityValidationItems?pa&&pa.getAttribute("validation_item")&&(a.accessibilityValidationItems=pa.getAttribute("validation_item")):a.accessibilityValidationItems=DEXT5.config.AccessibilityValidationItems;if("YYYYMMDD/"==I||"YYYYMM/"==I||"YYYY/"==I||"YYYY/MM/"==I||"YYYY/MM/DD/"==I||"/"==I||""==I)a.saveFolderNameRule=I;if("YYYYMMDD/"==J||"YYYYMM/"==J||"YYYY/"==J||"YYYY/MM/"==J||"YYYY/MM/DD/"==J||"/"==J||""==J)a.saveFileFolderNameRule=J;if("GUID"==na||"DATETIME"==na)a.saveFileNameRule=
na;var hb=DEXT5.util.xml.getNodeValue(e,"topmenu"),V=DEXT5.util.xml.getNodeValue(e,"toolbar"),ib=DEXT5.util.xml.getNodeValue(e,"toolbaradmin"),jb=DEXT5.util.xml.getNodeValue(e,"topstatusbar"),kb=DEXT5.util.xml.getNodeValue(e,"statusbar"),lb=DEXT5.util.xml.getNodeValue(e,"resizebar");a.top_menu="1"==hb?hb:"0";a.tool_bar="1"==V||"2"==V||"3"==V||"4"==V?V:"0";a.top_status_bar=""!=jb?jb:"1";a.status_bar="1"==kb?kb:"0";a.resize_bar="1"==lb?lb:"0";a.tool_bar_admin="1"==ib?ib:"0";""!=DEXT5.config.zTopMenu&&
(a.top_menu=DEXT5.config.zTopMenu);""!=DEXT5.config.zToolBar&&(a.tool_bar=DEXT5.config.zToolBar);""!=DEXT5.config.zTopStatusBar&&(a.top_status_bar=DEXT5.config.zTopStatusBar);""!=DEXT5.config.zStatusBar&&(a.status_bar=DEXT5.config.zStatusBar);""!=DEXT5.config.Mode?a.mode=DEXT5.config.Mode:"view"==DEXT5.util.xml.getNodeValue(e,"default_mode")&&(a.mode="view");var W="",W=0==D.length?DEXT5.rootPath:"/"==D.substring(0,1)?location.protocol+"//"+location.host:4<D.length&&"http"==D.substring(0,4).toLowerCase()?
"":DEXT5.rootPath;a.style.InitVisible=DEXT5.config.InitVisible;""!=DEXT5.config.DevelopLangage?a.developLang=DEXT5.config.DevelopLangage:0<H.length&&(a.developLang=H);if(0==D.length)switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.post_url=W+"handler/upload_handler.jsp";break;case "PHP":a.post_url=W+"handler/upload_handler.php";break;default:a.post_url=W+"handler/upload_handler.ashx"}else{if(4<D.length&&"http"==D.substring(0,4).toLowerCase()&&D.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host){var ca=
"";switch(H.toUpperCase()){case "JAVA":case "JSP":ca=DEXT5.rootPath+"handler/upload_handler.jsp";break;case "PHP":ca=DEXT5.rootPath+"handler/upload_handler.php";break;default:ca=DEXT5.rootPath+"handler/upload_handler.ashx"}a.proxy_url=ca}a.post_url=W+D}""!=a.userFieldValue&&(-1<a.post_url.indexOf("?")?a.post_url=a.post_url+"&"+a.userFieldID+"="+a.userFieldValue:a.post_url=a.post_url+"?"+a.userFieldID+"="+a.userFieldValue);""!=DEXT5.config.focusInitObjId&&(a.focusInitObjId=DEXT5.config.focusInitObjId);
""!=DEXT5.config.focusInitEditorObjId&&(a.focusInitEditorObjId=DEXT5.config.focusInitEditorObjId);""!=DEXT5.config.tabIndexObjId&&(a.tabIndexObjId=DEXT5.config.tabIndexObjId);""!=DEXT5.config.SetValueObjId&&(a.setValueObjId=DEXT5.config.SetValueObjId);""!=DEXT5.config.LoadedEvent&&(a.LoadedEvent=DEXT5.config.LoadedEvent);var A=DEXT5.util.xml.getNode(d,"license"),Pb=DEXT5.util.xml.getNodeValue(A,"product_key"),mb=DEXT5.util.xml.getNodeValue(A,"license_plugin"),nb=DEXT5.util.xml.getNodeValue(A,"plugin_use"),
ob=DEXT5.util.xml.getNodeValue(A,"image_editor_use"),qa=DEXT5.util.xml.getNodeValue(A,"plugin_version"),Qb=DEXT5.util.xml.getNodeValue(A,"print_preview"),pb=DEXT5.util.xml.getNodeValue(A,"print_header"),qb=DEXT5.util.xml.getNodeValue(A,"print_footer"),ra=DEXT5.util.xml.getNode(A,"mime_use"),rb=DEXT5.util.xml.getNodeValue(A,"mime_use"),Rb=DEXT5.util.xml.getNodeValue(A,"trust_sites");a.LicenseKey=DEXT5.util.xml.getNodeValue(A,"license_key");a.printPreview="1"==Qb?"1":"0";a.printHeader=pb;a.printFooter=
qb;a.basePrintHeader=pb;a.basePrintFooter=qb;a.trustSites=Rb;a.productKey=Pb;""!=mb&&(a.plugin_root=mb);a.plugInUse=""==DEXT5.config.pluginUse?0==nb.length?a.plugInUse:nb:DEXT5.config.pluginUse;0==a.plugInUse&&"ieplugin"==a.runtimes&&(a.plugInUse=1);a.imageEditorUse=""==DEXT5.config.imageEditorUse?0==ob.length?a.imageEditorUse:ob:DEXT5.config.imageEditorUse;""==DEXT5.config.mimeCharset?ra&&ra.getAttribute("mimeCharset")&&(a.mimeCharset=ra.getAttribute("mimeCharset")):a.mimeCharset=DEXT5.config.mimeCharset;
a.mimeUse=""==DEXT5.config.mimeUse?0==rb.length?a.mimeUse:rb:DEXT5.config.mimeUse;null!=qa&&7<=qa.length&&(a.plugin_version=qa);if(""==a.proxy_url&&("NET"==H.toUpperCase()||"JSP"==H.toUpperCase()||"JAVA"==H.toUpperCase()||"PHP"==H.toUpperCase()||"ASP"==H.toUpperCase())){var X=a.post_url;""!=a.userFieldValue&&(X=a.post_url.split("?")[0]);var L=DEXT5.ajax.load(X+"?dext=test");"CCODE_001"==a.custom_code&&(L=DEXT5.ajax.load(X+"?hello=test"));if(null==L||""==L){var C="",sa=0<DEXT5.config.InitXml.length?
sa:"dext_editor.xml";"ko"==a.lang||"ko-kr"==a.lang?(C="Editor\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n",C+=X+"\n\n",C+=sa+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(C="Editor's setting is not correct. Access the following URL is not valid.\n\n",C+=X+"\n\n",
C+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+sa+'."');alert(C);return}L=L.toLowerCase();-1<L.indexOf("hi, dext5 editor !!!!")&&-1<L.indexOf("-")&&(DEXT5.ServerReleaseVer=L.split("-")[1])}a.useLog="1"==DEXT5.config.useLog?"1":"0";this.editor=null;a.editor_id=b;this.FrameID="dext_frame_"+b;a.holderID="dext_frame_holder"+b;this.ID=b;var M="",sb=a.style.height;0==a.style.InitVisible&&(sb="1px");M='<div id="'+a.holderID+'" style="width:'+a.style.width+
"; height:"+sb+"; ";if(DEXT5.browser.iOS||DEXT5.browser.mobile)M+=" overflow:scroll; overflow-x:hidden; -webkit-overflow-scrolling:touch; ";M+='"></div>';if(""!=DEXT5.config.EditorHolder){var tb=document.getElementById(DEXT5.config.EditorHolder);tb?tb.innerHTML=M:document.write(M)}else document.write(M);var Sb=document.getElementById(a.holderID),v;try{v=document.createElement("<iframe frameborder='0' scrolling='no'>")}catch(Ub){v=document.createElement("iframe"),v.setAttribute("frameborder","0"),
v.setAttribute("scrolling","no")}v.setAttribute("id",this.FrameID);v.style.width="100%";v.style.height="100%";a.style.height.indexOf("%");if(DEXT5.browser.iOS||DEXT5.browser.mobile)v.style.overflow="hidden",v.style.display="inline-block";v.width="100%";v.height="100%";Sb.appendChild(v);var Tb=this,ub=function(){try{v.contentWindow.dext_frame_loaded_event(b,a,Tb)}catch(c){alert("ErrCode : 1001")}};v.addEventListener?v.addEventListener("load",ub,!1):v.attachEvent&&v.attachEvent("onload",ub);v.src=a.editor_url;
""!=a.custom_code&&DEXT5.util.CustomSetting("function",a.custom_code,a)}}}function CustomSettingFunction(b){"CCODE_001"==b.custom_code&&(b.empty_tag_remove="1",b.sourceViewtype="1",b.system_title="",b.tableAutoAdjust="0",b.accessibility="-1",b.tool_bar="2",b.top_menu="1",b.setDefaultStyle.value="2",b.setDefaultStyle.body_id="hello_body",b.emoticon_url=DEXT5.rootPath+"config/hello_emoticon.xml",b.forms_url=DEXT5.rootPath+"config/hello_formlist.xml")}
function CustomRemoveItem(b){var c=[];"CCODE_001"==b&&(c="save pagebreak copy cut paste doc_bg_image insert_link_media media_create entity iframe_create flash_create table_row_clone about insert_row_column grid tool_replace convert_table_to_text table_tool table_indent table_outdent row_property column_property align_vertical".split(" "));return c}
function replacePtOrCmToPx(b){try{for(var c=b.toLowerCase().split(" "),a=c.length,d,h,f="",k=0;k<a;k++){var g=c[k];-1<g.indexOf("pt")?(d=4*parseFloat(g)/3,0<d&&1>d&&(d=1),0>d&&(d=0),h=Math.round(d)+"px",f=""!=f?f+" "+h:h):-1<g.indexOf("cm")?(_cm=37.795275593333*parseFloat(g),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),h=Math.round(_cm)+"px",f=""!=f?f+" "+h:h):f=""!=f?f+" "+g:g}return""!=f?f:b}catch(e){return b}}window.DEXT5&&"samsung.net"==document.domain&&(window.HELLO=window.DEXT5,HelloEditor=Dext5editor);
function GetUserRunTimeEditor(b){b=b.toLowerCase();var c="";""==b||"html5"==b?c="html5":"ieplugin"==b?c=1==DEXT5.browser.ie&&12>DEXT5.browser.ieVersion?"ieplugin":"html5":-1<b.indexOf("ieplugin")&&8<b.length?(b=DEXT5.util.parseIntOr0(b),c=1==DEXT5.browser.ie&&b>=DEXT5.browser.ieVersion?"ieplugin":"html5"):c="html5";return c};
