-- v6.9.13

ALTER TABLE jmocha.tbl_forminfo ADD MOBILEDRAFTFLAG varchar(4) DEFAULT 'N' NULL COMMENT '전자결재S 모바일 기안 여부';
INSERT INTO TBL_TENANT_CONFIG (TENANT_ID, PROPERTY_NAME, CONFIG_NAME, PROPERTY_VALUE, DESCRIPTION, REGDATE, CONFIG_TYPE) VALUES (0, 'useMobileDraft', '모바일 기안하기 사용 여부', 'NO', '모바일 기안하기 사용 여부. YES: 사용, NO: 미사용 (default : NO)', '2025-08-22 00:00:00.000', '전자결재');
ALTER TABLE `JMOCHA_MAIL_GENERAL` ADD COLUMN IF NOT EXISTS `FORWARD_AS` VARCHAR(50) DEFAULT 'inline';
ALTER TABLE `JAMES_MAIL_SEARCH` ADD COLUMN IF NOT EXISTS `EACH_FLAG` TINYINT(1) DEFAULT 0;