-- v6.9.14

-- (이유정) 게시판 > 그룹게시판
ALTER TABLE tbl_board_boardinfo ADD USEGROUPFLAG char(1) DEFAULT 'N' NOT NULL;
delete from tbl_board_treecache;
update tbl_board_item_listoption set view_fg = 'N' where listtype = 'E' and sn = 0;

-- (김대현) 대용량 첨부파일 관리 컬럼 추가
 ALTER TABLE
            JMOCHA_BIGATTACH_DOWN_LIMIT
            ADD
            (FILE_NAME VARCHAR(100),
			FILE_SIZE BIGINT(20),
			USER_ID VARCHAR(80),
			UPLOAD_DATE VARCHAR(100));
			
-- (전인하)
INSERT INTO TBL_TENANT_CONFIG (TENANT_ID, PROPERTY_NAME, CONFIG_NAME, PROPERTY_VALUE, DESCRIPTION, REGDATE, CONFIG_TYPE) VALUES (0, 'draftAllTypeB', '일괄기안 B타입', 'N', '일괄기안 B타입 한글문서만 가능하며 헤더 부분에 headcampaign 값이 필수로 존재해야 한다.', '2025-01-08 00:00:00.000', '전자결재G');

DROP TABLE IF EXISTS `TBL_APPROVE_ERROR_INFO`;
CREATE TABLE `TBL_APPROVE_ERROR_INFO` (
  `DOCID` varchar(80) NOT NULL COMMENT '문서 아이디',
  `TENANT_ID` mediumint(5) NOT NULL DEFAULT 0 COMMENT '테넌트 아이디',
  `COMPANYID` varchar(20) NOT NULL COMMENT '회사 아이디',
  `ERROR_MESSAGE` varchar(2000) DEFAULT NULL COMMENT '오류 메시지',
  `ERROR_CASE` varchar(200) DEFAULT NULL COMMENT '커스텀 오류 케이스',
  PRIMARY KEY (`TENANT_ID`,`COMPANYID`,`DOCID`),
  KEY `tbl_approve_file_error_IDX` (`DOCID`,`TENANT_ID`,`COMPANYID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='백단에서 결재 시 본문 물리파일을 핸들링하다가 오류가 발생한 doc을 넣는 테이블';

-- (황인경) 포탈
UPDATE tbl_portal_theme
SET THEME_CONTENT6='Tema dengan desain yang menampilkan berita dan area atas.'
WHERE theme_id=1;

UPDATE tbl_portal_theme
SET THEME_CONTENT6='Tema dengan area informasi dan pintasan di bagian atas.'
WHERE theme_id=2;

UPDATE tbl_portal_theme
SET THEME_CONTENT6='Tema yang memungkinkan fokus pada portlet tanpa area tetap yang terkait dengan informasi.'
WHERE theme_id=3;

UPDATE tbl_portal_theme
SET THEME_CONTENT6='Tema untuk Mobile'
WHERE theme_id=4;

ALTER TABLE tbl_portal_theme ADD THEME_NAME4 varchar(100) DEFAULT 'theme4' NULL;
ALTER TABLE tbl_portal_theme ADD THEME_NAME5 varchar(100) DEFAULT 'theme5' NULL;
ALTER TABLE tbl_portal_theme ADD THEME_NAME6 varchar(100) DEFAULT 'theme6' NULL;


UPDATE tbl_portal_theme
SET THEME_NAME4='基本型', THEME_NAME5='Dạng cơ bản', THEME_NAME6='Tipe dasar'
WHERE theme_id=1;

UPDATE tbl_portal_theme
SET THEME_NAME4='快捷型', THEME_NAME5='Dạng lối tắt', THEME_NAME6='Tipe pintasan'
WHERE theme_id=2;

UPDATE tbl_portal_theme
SET THEME_NAME4='信息分离型', THEME_NAME5='Dạng tách biệt thông tin', THEME_NAME6='Tipe pemisahan informasi'
WHERE theme_id=3;

UPDATE tbl_portal_theme
SET THEME_NAME4='theme4', THEME_NAME5='theme4', THEME_NAME6='theme4'
WHERE theme_id=4;

-- 회람판
UPDATE TBL_CIRCULAR_LISTOPTION SET width = '70' WHERE name1 = '확인';

-- 공통 포틀릿 & 캐비넷
UPDATE tbl_cb_cabinet SET cabinet_name2='My Cabinet' WHERE cabinet_name1 = '나의캐비넷';
UPDATE tbl_cb_cabinet SET cabinet_name2='Resource' WHERE cabinet_name1 = '자원관리';
UPDATE tbl_cb_cabinet SET cabinet_name2='Circular' WHERE cabinet_name1 = '회람판';
UPDATE tbl_cb_cabinet SET cabinet_name2='Journal' WHERE cabinet_name1 = '업무일지';
UPDATE tbl_cb_cabinet SET cabinet_name2='Contacts' WHERE cabinet_name1 = '주소록';
UPDATE tbl_cb_cabinet SET cabinet_name2='Mail' WHERE cabinet_name1 = '메일';
UPDATE tbl_cb_cabinet SET cabinet_name2='Community' WHERE cabinet_name1 = '커뮤니티';
UPDATE tbl_cb_cabinet SET cabinet_name2='Schedule' WHERE cabinet_name1 = '일정관리';
UPDATE tbl_cb_cabinet SET cabinet_name2='Board' WHERE cabinet_name1 = '게시판';
UPDATE tbl_cb_cabinet SET cabinet_name2='Approval' WHERE cabinet_name1 = '전자결재';

-- 가온아이용 포틀릿 & 캐비넷
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (1, 1, 6, 0, 'Top', 'Email');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (2, 4, 6, 0, 'Top', 'Pengumuman');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (4, 15, 6, 0, 'Top', 'Pemungutan Suara');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (5, 0, 6, 0, 'Top', 'Jajak Pendapat Cepat');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (6, 2, 6, 0, 'Top', 'Jadwal');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (7, 3, 6, 0, 'Top', 'Daftar Persetujuan');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (8, 3, 6, 0, 'Top', 'Formulir Favorit');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (9, 4, 6, 0, 'Top', 'Galeri Foto');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (10, 4, 6, 0, 'Top', 'Papan Favorit');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (11, 5, 6, 0, 'Top', 'Komunitas');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (12, 0, 6, 0, 'Top', 'Bantuan');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (14, 0, 6, 0, 'Top', 'Cuaca');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (26, 0, 6, 0, 'Top', 'Ulang Tahun');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (34, 0, 6, 0, 'Top', 'Gambar Slide');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (36, 0, 6, 0, 'Top', 'Info Pengguna');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (47, 4, 6, 0, 'Top', 'Papan Film');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (49, 0, 6, 0, 'Top', 'Jumlah');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (50, 35, 6, 0, 'Top', 'workspace');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (51, 6, 6, 0, 'Top', 'Sumber Daya');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (52, 10, 6, 0, 'Top', 'Folder Saya');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (53, 42, 6, 0, 'Top', 'Survei');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (54, 6, 6, 0, 'Top', 'Sumber Daya');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (70, 10, 6, 0, 'Top', 'Folder Saya');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (73, 42, 6, 0, 'Top', 'Survei');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (74, 3, 6, 0, 'Top', 'Bagan');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (75, 4, 6, 0, 'Top', 'Tab Papan');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (80, 4, 6, 0, 'Top', '공지사항_in');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (81, 4, 6, 0, 'Top', '공지사항_in');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (82, 4, 6, 0, 'Top', '가온아이행사_in');
INSERT INTO TBL_PORTAL_PORTLET_NAME (PORTLET_ID, MENU_ID, PORTLET_LANG, TENANT_ID, COMPANY_ID, PORTLET_NAME) VALUES (83, 0, 6, 0, 'Top', 'Homepage');

-- (김승연) 
CREATE TABLE TBL_SAML_REQUEST_ID (
    REQUEST_ID VARCHAR(40) NOT NULL,
    CREATE_DT DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TBL_TENANT_CONFIG (TENANT_ID, PROPERTY_NAME, CONFIG_NAME, PROPERTY_VALUE, DESCRIPTION, REGDATE, CONFIG_TYPE) VALUES (0, 'useTigrisSAMLAuth', 'tigris SAML 인증 연동여부', 'NO', 'YES: 연동NO: 연동안함 (default: NO)', '2025-07-23 00:00:00', '연동');
