/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class egovframework_let_utl_fcc_service_KlibUtil_KlibCipher */

#ifndef _Included_egovframework_let_utl_fcc_service_KlibUtil_KlibCipher
#define _Included_egovframework_let_utl_fcc_service_KlibUtil_KlibCipher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     egovframework_let_utl_fcc_service_KlibUtil_KlibCipher
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_egovframework_let_utl_fcc_service_KlibUtil_00024KlibCipher_encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     egovframework_let_utl_fcc_service_KlibUtil_KlibCipher
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_egovframework_let_utl_fcc_service_KlibUtil_00024KlibCipher_decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
