package egovframework.ezEKP.ezSystem.vo;

public enum CheckName {
	DomainName,	
	BigSizeMailAttachDelDay,
	BigSizeMailAttachLimit,
	totBigSizeMailAttachLimit,	
	INDIVIDUALMAILUSER,
	IS_READ_DELETE,
	MailAttachLimit,
	PrimaryLang,
	PrimaryTimeZone,
	USE_FileExtension,
	ExpirePassPeriod,
	LicenseKey,
	Use_FromAddress,
	MaxAllowedCountOfLoginFail,
	USE_HTMLMODE,
	editorFontStyle,
	useSession,
	useSessionMobile,
	useMailConfirm,
	MailBigSizeAttachDownloadLimitCount,
	MailBigSizeAttachLimitCount,
	ApprTotalAttachLimit,
	ApprAttachLimit,
	BigSizeApprAttachLimit,
	ApprBigSizeAttachDownloadLimitCount,
	ApprBigSizeAttachLimitCount,
	BigSizeApprAttachDelDay,
	useEachMailDefault,
	useAutoZipEnc
}
