#-----------------------------------------------------------------------
#
#   apprCode.properties 
#   \uc804\uc790\uacb0\uc7ac \ucf54\ub4dc
#   
#-----------------------------------------------------------------------
#\uc804\uc5ed \ubcc0\uc218 \uc815\uc758


appr.staDTDraftDoc   = A01001		
#\uae30\uc548\ubb38
appr.staDTReportDoc  = A01002		
#\ubcf4\uace0\ubb38
appr.staDTReceiptDoc = A01003
#\uc218\uc2e0\ubb38
appr.staDTExcuteDoc  = A01004
#\uc2dc\ud589\ubb38
appr.staDTHabyuiDoc  = A01005
#\ud569\uc758\ubb38
appr.staDTGamsaDoc   = A01006
#\uac10\uc0ac\ubb38
appr.staDTApplyDoc   = A01007
#\uc2e0\uccad\uc11c
appr.staDSPumYui  = A02001
#\ud488\uc758
appr.staDSHyubJo  = A02002
#\ud611\uc870
appr.staDSGamSa   = A02003
#\uac10\uc0ac
appr.staDSSimSa   = A02004
#\uc2ec\uc0ac
appr.staDSSuSin   = A02011
#\uc218\uc2e0
appr.staDSHabYui  = A02012
#\ud569\uc758
appr.staDSSiHang  = A02013
#\uc2dc\ud589
appr.staDSGamSaBu = A02014
#\uac80\uc0ac\ubd80 \uac10\uc0ac
appr.staDSGongRam = A02015
#\uacf5\ub78c
appr.staDSHoiRam  = A02016
#\ud68c\ub78c
appr.staDSChamJo  = A02017
#\ucc38\uc870
appr.staDSWhokyul = A02018
#\ud6c4\uacb0
appr.staDSBalsin  = A02019
#\ubc1c\uc2e0
appr.staDSApply   = A02020
#\uc2e0\uccad
appr.staDSBansong = A02031
#\ubc18\uc1a1
appr.staDSHesong  = A02032
#\ud68c\uc1a1

#AprType

appr.staATYilBan  = A03001
#\uc77c\ubc18
appr.staATGyulJe  = A03001
#\uacb0\uc7ac
appr.staatwhoakin = A03002
#\ud655\uc778
appr.staATAnHam   = A03003
#\uacb0\uc7ac\uc548\ud568
appr.staATJunGyul = A03004
#\uc804\uacb0
appr.staATGamSa   = A03005
#\uac10\uc0ac
appr.staATSimSa   = A03006
#\uc2ec\uc0ac
appr.staATChamJo  = A03007
#\ucc38\uc870
appr.staATSoonChaHyubJo   = A03008
#\uac1c\uc778\uc21c\ucc28\ud611\uc870
appr.staATHapYu   = A03008
#\uac1c\uc778 \ud569\uc758
appr.staATByungRyulHyubJo = A03009
#\uac1c\uc778\ubcd1\ub82c\ud611\uc870
appr.staATBuSeuSoonChaHyubJo   = A03011
#\ubd80\uc11c\uc21c\ucc28\ud611\uc870
appr.staATBuSeuByungRyulHyubJo = A03012
#\ubd80\uc11c\ubcd1\ub82c\ud611\uc870
appr.staATGamSaBu     = A03013
#\uac10\uc0ac(\ubd80\uc11c\uac10\uc0ac)
appr.staATSuSin       = A03014
#\uc218\uc2e0
appr.staATWhokyul     = A03015
#\ud6c4\uc5f4
appr.staATGongram     = A03017
#\uacf5\ub78c
appr.staATTongje      = A03031
#\ud1b5\uc81c. 031~039\ub294 \ud655\uc778\uacfc \ub3d9\uc77c.
appr.staATReserved2	= A03032
#031~035\ub294 \ud655\uc778\uacfc \ub3d9\uc77c.
appr.staATReserved3	= A03033
#031~035\ub294 \ud655\uc778\uacfc \ub3d9\uc77c.
appr.staATReserved4	= A03034
#031~035\ub294 \ud655\uc778\uacfc \ub3d9\uc77c.
appr.staATReserved5	= A03035
#031~035\ub294 \ud655\uc778\uacfc \ub3d9\uc77c.
appr.staATWhokyul2	= A03040
#\ud6c4\uacb0

#Aprappr.state

appr.staASmikyul  = A04000
#\ubbf8\uacb0
appr.staASDaeGi   = A04001
#\ub300\uae30
appr.staASJinHang = A04002
#\uc9c4\ud589
appr.staASSungIn  = A04003
#\uc2b9\uc778
appr.staASBanSong = A04004
#\ubc18\uc1a1
appr.staASBoRyu   = A04005
#\ubcf4\ub958
appr.staASWheSu   = A04006
#\ud68c\uc218
appr.staASAprEND  = A04010
#\uc644\ub8cc
appr.staASDoJak   = A04011
#\ub3c4\ucc29
appr.staASJiJung  = A04012
#\uc9c0\uc815
appr.staASJubSu   = A04013
#\uc811\uc218
appr.staASBaeBu   = A04014
#\ubc30\ubd80
appr.staASWheSong = A04015
#\ud68c\uc1a1
appr.staASSusinJinHang    = A04016
#\uc218\uc2e0\uc9c4\ud589
appr.staASSusinSungIn     = A04017
#\uc218\uc2e0\uc644\ub8cc
appr.staASSusinJiJung     = A04018
#\uc218\uc2e0\uc9c0\uc815

#OpinionType

appr.staIlBan     = A17001
#\uc77c\ubc18\uc758\uacac
appr.staBanSong   = A17002
#\ubc18\uc1a1\uc758\uacac
appr.staBoRyu     = A17003
#\ubcf4\ub958\uc758\uacac
appr.staWheSong   = A17004
#\ud68c\uc1a1\uc758\uacac