#-----------------------------------------------------------------------
#
#   config.properties 
#   
#-----------------------------------------------------------------------

#################### \uadf8\ub8f9\uc6e8\uc5b4 \uad00\ub828 config ####################

#YES \uc774\uba74 \uc0ac\uc6d0\ucd94\uac00 \ubc0f \ub85c\uadf8\uc778\uc2dc \uc544\uc774\ub514 \ub300\ubb38\uc790\uccb4\ud06c \uc0ac\uc6a9.NO \uc774\uba74 \uc0ac\uc6a9\ud558\uc9c0 \uc54a\ub294\ub2e4.
config.USE_CHECKUPSTR = YES
#YES \uc774\uba74 \ub3c4\ub85c\uba85\uc8fc\uc18c \uc624\ud508API \uc0ac\uc6a9. NO \uc774\uba74 \uc0ac\uc6a9\uc548\ud568.
config.USE_AddressOpenAPI = YES
#\ub3c4\ub85c\uba85\uc8fc\uc18c \uc2b9\uc778\ud0a4
config.ConfirmKey = U01TX0FVVEgyMDE2MTEwNzE1NDMzMDE2MzM4
#\ud3ec\ud0c8 \uc0c8\ub85c\uace0\uce68 \uc2dc\uac04 \uc9c0\uc815
config.refreshSecond = 300
#\uad00\ub9ac\uc790 \ud654\uba74 ActiveX \uc124\uce58\uc5ec\ubd80
config.AdminActiveX = YES
config.UsePrimaryLangOnly = NO
config.UserInfo_ApprovalG = YES
###################### \uba54\uc77c \uad00\ub828 config #####################

#\ubaa8\ub4c8\uc0ac\uc6a9 \uc720\ubb34
config.IsJMochaStandAlone = NO
#\uba54\uc77c\uc11c\ubc84 \uc8fc\uc18c
config.MailServerAddress = 10.0.102.8
#JMocha Gateway \uc11c\ubc84 \uc8fc\uc18c
config.JGwServerURL = http://10.0.102.8:9090/jgw_server
#JMocha Super Password
config.JMochaSuperPassword = ENC(mS2qooiqdwsgKwG8NLlYLmQxWB6Mg80J)
#IMAP \ud3ec\ud2b8\ubc88\ud638
config.IMAPPort = 143
#SMTP \ud3ec\ud2b8\ubc88\ud638
config.SMTPPort = 25
#\ud074\ub7ec\uc2a4\ud130 \ud658\uacbd(2\uac1c \uc774\uc0c1\uc758 \uc6f9\uc11c\ubc84)\uc5d0\uc11c \uc2a4\ucf00\uc904\ub7ec \uc120\ud0dd \uc2dc \uc0ac\uc6a9\ub418\ub294 \uac12.
config.SchedulerServer = 1
#\uc2a4\ucf00\uc904\ub7ec \ub3d9\uc791 \uc5ec\ubd80
config.Run_Scheduler = YES

###################### \ud30c\uc77c \uad00\ub828 config #####################

#MHT \uad00\ub828 \uacbd\ub85c
config.LocalPath = /files/upload_common/mhtImage/
#\ud30c\uc77c\uacbd\ub85c
data_root = C:/javaide/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ezFlow4Java
upload_board.BOARDBACKGROUND = /files/upload_board/backGroundImage
upload_board.TEMPUPLOADFILE = /files/upload_board/tempUploadFile
upload_board.ROOT = /files/upload_board
upload_board.FORM = /files/upload_board/form
upload_board.UPLOADQUESTION = /files/upload_board/uploadQuestion
upload_common.ROOT = /files/upload_common
upload_common.MHTIMAGE = /files/upload_common/mhtImage
upload_common.DOCDOWNLOAD = /files/upload_common/docDownload
upload_personal.ROOT = /files/upload_personal
upload_personal.PHOTO = /files/upload_personal/photo
upload_personal.PHOTOTEMP = /files/upload_personal/photo/temp
upload_approval.ROOT = /files/upload_approval
upload_approval.SEALIMGTEMP = /files/upload_approval/sealImg/temp
upload_approval.SEALIMG = /files/upload_approval/sealImg
upload_approval.SIGNIMGS = /files/upload_approval/signImgs
upload_approvalG.SIGNIMGS = /files/upload_approvalG/signImgs
upload_approvalG.ROOT = /files/upload_approvalG
upload_approvalG.SEALIMG = /files/upload_approvalG/sealImg
upload_community.ROOT = /files/upload_community
upload_community.LOGO = /files/upload_community/logo
upload_community.FILEDATA = /files/upload_community/filedata
upload_community.PDS = /files/upload_community/filedata/pds
upload_community.PDS1 = /files/upload_community/filedata/pds1
upload_community.MAINBOARD = /files/upload_community/filedata/mainboard
upload_mail.ROOT = /files/upload_mail
upload_mail.RESERVED_MAIL_PATH = /files/upload_mail/reservedMails
upload_mail.SIGNIMGS = /files/upload_mail/MailSignImage
upload_portal.ROOT = /files/upload_portal
upload_schedule.ROOT = /files/upload_schedule

##################### \ucd94\ud6c4\uc5d0 \uc0ad\uc81c \ubc0f \ubcc0\uacbd\ud574\uc57c\ub428 #####################
#\ud68c\uc0ac\uba85
config.companyNum = S907000
#\ubb38\uc11c \uc5f4\ub78c \uad8c\ud55c \uc815\uc758 : \ubb38\uc11c \uc5f4\ub78c \uad8c\ud55c\uc744 \uc815\uc758\ud55c\ub2e4.1 : \uacf5\uac1c/\ubd80\ubd84\uacf5\uac1c/\ube44\uacf5\uac1c \uad8c\ud55c \uccb4\ud06c.2 : \ubcf4\uc548\ub4f1\uae09 \uad8c\ud55c \uccb4\ud06c.3 : \uc5f4\ub78c\uad8c\ud55c \uccb4\ud06c.\ube44\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, \uc774\uacf3\uc5d0 \uc18d\ud558\uba74 \uc5f4\ub78c \uac00\ub2a5.\uc18d\ud558\uc9c0 \uc54a\uc73c\uba74, 2\ubc88, 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.\ubd80\ubd84\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, \uc774\uacf3\uc5d0 \uc18d\ud558\uba74 \uc5f4\ub78c \uac00\ub2a5.\uc18d\ud558\uc9c0 \uc54a\uc73c\uba74, 2\ubc88, 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, 2\ubc88 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.
config.UserInfo_ApprovalG_VIEW = YYY

########################################################
####################### \uac80\uc0c9 \ud6c4 \uc18c\uc2a4 \ubcc0\uacbd #####################

#IE 11 \uc5d0\ub514\ud130 \uc124\uc815 "" \ub610\ub294 CK
config.IE11EDITOR = CK

####################### \uc0ad\uc81c  #####################

config.Use_ezDMS = NO
config.Use_MobileMgmt = NO
config.USE_OCS = NO
config.Use_ezKMS = NO
#SSL \uc0ac\uc6a9\uc5ec\ubd80 \uc124\uc815
config.ezInfoSSL = 
