#-----------------------------------------------------------------------
#
#   config.properties 
#   
#-----------------------------------------------------------------------
config.Use_ezKMS = N
config.Use_ezDMS = N
config.Use_Portal = Y
config.Use_MobileMgmt = N
config.UserInfo_ApprovalG = N
config.ServerName = test.yoonz44.com
config.Use_MultiData = Y
config.lang_Primary1 = \ud55c\uae00
config.lang_Primary2 = Korean
config.lang_Primary3 = Korean
config.lang_Primary4 = Korean
config.lang_Secondary1 = \uc601\ubb38
config.lang_Secondary2 = English
config.lang_Secondary3 = English
config.lang_Secondary4 = English
config.primary = 1
config.Use_OCS = "YES"
config.editor = "";
config.IE11editor = "";