#-----------------------------------------------------------------------
#
#   config.properties 
#   
#-----------------------------------------------------------------------

#################### \uadf8\ub8f9\uc6e8\uc5b4 \uad00\ub828 config ####################

#YES \uc774\uba74 \ub3c4\ub85c\uba85\uc8fc\uc18c \uc624\ud508API \uc0ac\uc6a9. NO \uc774\uba74 \uc0ac\uc6a9\uc548\ud568.
config.USE_AddressOpenAPI = YES
#\ub3c4\ub85c\uba85\uc8fc\uc18c \uc2b9\uc778\ud0a4
config.ConfirmKey = U01TX0FVVEgyMDIwMTIyMzExMTYxNjExMDU4NTE=
#\ub3c4\ub85c\uba85\uc8fc\uc18c Open API \uc11c\ubc84 \ub3c4\uba54\uc778
config.jusoDomain = business.juso.go.kr
#\ud3ec\ud0c8 \uc0c8\ub85c\uace0\uce68 \uc2dc\uac04 \uc9c0\uc815
config.refreshSecond = 300
#\uad00\ub9ac\uc790 \ud654\uba74 ActiveX \uc124\uce58\uc5ec\ubd80
config.AdminActiveX = NO
config.UsePrimaryLangOnly = NO
config.UserInfo_ApprovalG = YES
# DB \uae30\ubc18 \uc138\uc158 \ubc29\uc2dd \uc635\uc158
config.UseDbSession = YES
###################### \uba54\uc77c \uad00\ub828 config #####################

#IMAP \ud45c\uc900 \ud3f4\ub354 \uc544\uc774\ub514 \uc0ac\uc6a9 \uc720\ubb34
config.useStandardFolderId = YES

#\uba54\uc77c\uc11c\ubc84 \uc8fc\uc18c
config.MailServerAddress = jdev.kaoni.com
#\uc804\uc790\uacb0\uc7ac \ubaa8\ub4c8 \ub4f1\uc5d0\uc11c \uc54c\ub9bc \uba54\uc77c\uc744 \ubcf4\ub0b4\ub294 \uacbd\uc6b0 \ubcf4\ub0b8 \ud3b8\uc9c0\ud568\uc5d0 \uc800\uc7a5 \uc5ec\ubd80(\ud0c0 \uba54\uc77c \uc11c\ubc84\ub97c \uc774\uc6a9\ud574 \uc54c\ub9bc \uba54\uc77c\uc744 \ubcf4\ub0b4\ub294 \uacbd\uc6b0\ub97c \uc704\ud574 \ucd94\uac00\ud568)
config.SentMailStoredInSentbox = YES
#config.MailServerAddress = 222.106.242.179

# useMailServer2\ub294 \ud3ec\ud0c8> \uc678\ubd80\uba54\uc77c(\uce74\uc6b4\ud2b8,\uc6a9\ub7c9,\ud074\ub9ad)\uc744 \uc704\ud55c \uc635\uc158
config.useMailServer2 = N
# useMailServerPwSync\ub294 \uc678\ubd80\uba54\uc77c(\ube44\ubc00\ubc88\ud638 \ub3d9\uae30\ud654)\ub97c \uc704\ud55c \uc635\uc158
config.useMailServerPwSync = N
config.MailServerURL2 = http://jrelo.kaoni.com

#JMocha Gateway \uc11c\ubc84 \uc8fc\uc18c
#config.JGwServerURL = http://127.0.0.1:9090/jgw_server
config.JGwServerURL = http://jdev.kaoni.com:9090/jgw_server
#config.JGwServerURL = http://222.106.242.180:9091/jgw_server
#config.JGwServerURL = http://222.106.242.179:9090/jgw_server

#\ubaa8\ubc14\uc77c\uc6f9 \uba54\uc77c\uc5d0\uc11c \uc778\ub77c\uc778 \uc774\ubbf8\uc9c0\ub97c \ucc98\ub9ac\ud558\ub294 URL
config.MobileDownloadInline = /ezEmail/downloadInline.do
#JMocha Super Password
config.JMochaSuperPassword = ENC(mS2qooiqdwsgKwG8NLlYLmQxWB6Mg80J)
#IMAP \ud3ec\ud2b8\ubc88\ud638
config.IMAPPort = 143
#SMTP \ud3ec\ud2b8\ubc88\ud638
config.SMTPPort = 25
config.BizmekaAPIGateURL = https://gwx.bizmeka.com/myoffice/ezAPI/ezAPIGate.aspx
#\ud074\ub7ec\uc2a4\ud130 \ud658\uacbd(2\uac1c \uc774\uc0c1\uc758 \uc6f9\uc11c\ubc84)\uc5d0\uc11c \uc2a4\ucf00\uc904\ub7ec \uc120\ud0dd \uc2dc \uc0ac\uc6a9\ub418\ub294 \uac12.
config.SchedulerServer = 1
#\uc2a4\ucf00\uc904\ub7ec \ub3d9\uc791 \uc5ec\ubd80
config.Run_Scheduler = YES
#\ubb38\uc11c\uc720\ud1b5 \uc2a4\ucf00\uc974\ub7ec \ub3d9\uc791\uc5ec\ubd80
config.Run_RelayScheduler = NO
#\uc2a4\ucf00\uc904\ub7ec \ub3d9\uc791\uc2dc\uac04
config.cron.autoDelete = 00 00 05 * * *
config.cron.reservedMailSend = 00 0/10 * * * *
config.cron.processMailStatLogs = 30 01 00 * * *
config.cron.dailyFileManage = 30 02 00 * * *
config.cron.boardGarbageClear = 00 00 02 * * *
config.cron.boardNotiEndAlram = 00 00 02 * * *
config.cron.communityGarbageClear = 00 00 02 * * *
config.cron.apprStatisticsDailybatch = 55 55 23 * * *
config.cron.broadcastQuotaWarning = 00 00 02 * * *
config.cron.deleteAllUserOldMail = 00 30 00 * * *
config.cron.useDistributionoDelete = 00 00 02 * * *
config.cron.autoDeleteOfRetireUser = 00 30 02 * * *
config.cron.deleteDbSessionByTime = 00 15 02 * * *
config.cron.dailyApprFileManage = 00 05 00 * * *
config.cron.autoDeleteApprMailHistory = 00 00 03 * * *
config.cron.deleteOldApprMailHistory = 00 30 03 * * *
config.cron.checkReminder = 00 0/30 * * * *
config.cron.deleteFidoSessionByTime = 00 05 03 * * *
config.fixedDelay.susinScheduler = 60000
config.cron.deleteStatMenu = 00 00 01 * * *
config.cron.getTeamsIdFromGraphApi = 0 0 6 * * *
config.cron.getPresenceFromGraphApi = 0 0/1 * * * *
config.cron.setAdminAuthToken = 0 0/30 * * * *

#ezPMS \uc2a4\ucf00\uc974\ub7ec \ub3d9\uc791
config.crone.pmsUpdateLateStatus = 00 20 00 * * *
config.cron.mailboxQuotaListUpdate = 00 15 * * * *
config.cron.autoSetAnnualHoliday = 01 00 00 * * *
config.cron.weatherUpdate = 00 1/10 * * * *
config.cron.sendMailToSurveyParticipant = 00 40 00 * * *
config.cron.autoSetDailyWork = 00 10 00 * * *
config.cron.checkGoogleToken = 00 5/35 * * * *
config.cron.deleteOldNotification = 00 00 00 * * *

#\uc870\uc9c1\ub3c4 \uc0ac\uc6d0 \ucd94\uac00,\uc218\uc815\uc2dc \uacf5\uc6a9\ubc30\ud3ec\uadf8\ub8f9 \uc0dd\uc131,\uc218\uc815 \uc0ac\uc6a9 \uc5ec\ubd80
config.userRankMail = YES

###################### AI config #####################

# ezAI python \uc11c\ubc84
config.ezAIUrl = https://ezai-jrel.kaoni.com
config.apiKey = CUdGiuHFLNzNUg5JDxJHn70/E4oyh2H4rN6pxw2PZSw8OGt+QsmpZU6pLrl8XfuMV2ORIA/pPiUw35qY7buvvA==

###################### \ud30c\uc77c \uad00\ub828 config #####################

#MHT \uad00\ub828 \uacbd\ub85c
config.LocalPath = /files/upload_common/mhtImage/
#\ud30c\uc77c\uacbd\ub85c
upload_board.BOARDBACKGROUND = /files/upload_board/backGroundImage
upload_board.TEMPUPLOADFILE = /files/upload_board/tempUploadFile
upload_board.ROOT = /files/upload_board
upload_board.FORM = /files/upload_board/form
upload_board.UPLOADQUESTION = /files/upload_board/uploadQuestion
upload_common.ROOT = /files/upload_common
upload_common.MHTIMAGE = /files/upload_common/mhtImage
upload_common.DOCDOWNLOAD = /files/upload_common/docDownload
upload_personal.ROOT = /files/upload_personal
upload_personal.PHOTO = /files/upload_personal/photo
upload_personal.PHOTOTEMP = /files/upload_personal/photo/temp
upload_personal.PHOTOTHUMBNAIL = /files/upload_personal/photo/thumbnail
upload_approvalG.SIGNIMGS = /files/upload_approvalG/signImgs
upload_approvalG.ROOT = /files/upload_approvalG
upload_approvalG.SEALIMG = /files/upload_approvalG/sealImg
upload_community.ROOT = /files/upload_community
upload_community.LOGO = /files/upload_community/logo
upload_community.FILEDATA = /files/upload_community/filedata
upload_community.PDS = /files/upload_community/filedata/pds
upload_community.PDS1 = /files/upload_community/filedata/pds1
upload_community.MAINBOARD = /files/upload_community/filedata/mainboard
upload_community.TEMPUPLOADFILE = /files/upload_community/tempUploadFile
upload_mail.ROOT = /files/upload_mail
upload_mail.RESERVED_MAIL_PATH = /files/upload_mail/reservedMails
upload_mail.SIGNIMGS = /files/upload_mail/MailSignImage
upload_webfolder.ROOT = /files/upload_webfolder
upload_mail.LETTER = /files/upload_mail/letterBoxUpload
upload_portal.ROOT = /files/upload_portal
upload_schedule.ROOT = /files/upload_schedule
upload_circular.ROOT = /files/upload_circular
upload_task.ROOT = /files/upload_task
upload_journal.ROOT = /files/upload_journal
upload_vote.ROOT = /files/upload_vote
upload_cabinet.ROOT = /files/upload_cabinet
upload_attitude.ROOT = /files/upload_attitude
upload_attitude.TEMPUPLOAD = /files/upload_attitude/tempUpload
upload_ezOrgan.ROOT = /files/upload_ezOrgan
upload_car.ROOT = /files/upload_car
upload_car.TEMPUPLOAD = /files/upload_car/tempUploadFile
## \ubbfc\uc11d \ucd94\uac00
upload_project.ROOT = /files/upload_project
upload_survey.ROOT = /files/upload_survey
upload_newPortal.ROOT = /files/upload_newPortal
upload_resource.ROOT = /files/upload_resource
upload_resource.TEMPUPLOAD = /files/upload_resource/tempUploadFile
# 2023-12-18 \ud64d\uc2b9\ube44 - \uc790\uc6d0\uad00\ub9ac > \uc790\uc6d0\uc608\uc57d, \uc790\uc6d0\uc591\uc2dd \ubcf8\ubb38\uc5d0 \uc5c5\ub85c\ub4dc\ub418\ub294 \uc774\ubbf8\uc9c0 \uc804\uc6a9 \uacbd\ub85c \ucd94\uac00
upload_resource.CONTENT = /files/upload_resource/content
## \uba54\uc77c \ud15c\ud50c\ub9bf
upload_mail.MAILTEMPLATE = /files/upload_mail/mailTemplate
# 2025-02-25 \uc774\uac00\uc740 - \uc804\uc790\uacb0\uc7ac > \uc5f0\ub3d9 \ucca8\ubd80\ud30c\uc77c \uacbd\ub85c \ucd94\uac00
upload_approvalG.CONNATTACH = /files/upload_approvalG/connAttach

####################### \ubaa8\ubc14\uc77c \uad00\ub828 config #####################
config.mobileGwServerURL = http://127.0.0.1:80
# \uac8c\uc774\ud2b8\uc6e8\uc774 rest api \ud638\ucd9c \ud5c8\uc6a9 IP
config.mobileClientServerURL = 127.0.0.1

upload_relay.ROOT = /relay
upload_relay.R_DocPath = /files/upload_approvalG
USE_RECEIVEERR_FILE_MOVE_RECEIVETEMP = YES
USE_EMAIL_NOTIFICATION = YES
USE_RECEIVETEMPERR_ALERT = YES

#\ubb38\uc11c\uc720\ud1b5\uc5d0\uc11c \uc1a1\uc2e0 \ubc0f \uc218\uc2e0\uc5d0 \uc774\uc6a9\ub418\ub294 \uae30\uad00\ucf54\ub4dc
config.companyNum = S907000
#\ubb38\uc11c\uc720\ud1b5\uc5d0\uc11c \uc218\uc2e0\ud55c \uc911\uacc4\ubb38\uc11c \uc591\uc2dd ID \uc870\ud68c\uc6a9\ub3c4\ub85c\uc0ac\uc6a9? 10\uae00\uc790
Relay_FormID = 9999999999

#\uc6d0\ubb38\uacf5\uac1c
config.useOpenGov = NO
openGov_companyNum = B551365
openGov_companyName = \ud55c\uad6d\ub514\uc790\uc778\uc9c4\ud765\uc6d0
openGov_root = /Users/hyojin/app/workspace/ezFlow4Java/output/ezFlow


##################### \ucd94\ud6c4\uc5d0 \uc0ad\uc81c \ubc0f \ubcc0\uacbd\ud574\uc57c\ub428 #####################
#\ubb38\uc11c \uc5f4\ub78c \uad8c\ud55c \uc815\uc758 : \ubb38\uc11c \uc5f4\ub78c \uad8c\ud55c\uc744 \uc815\uc758\ud55c\ub2e4.1 : \uacf5\uac1c/\ubd80\ubd84\uacf5\uac1c/\ube44\uacf5\uac1c \uad8c\ud55c \uccb4\ud06c.2 : \ubcf4\uc548\ub4f1\uae09 \uad8c\ud55c \uccb4\ud06c.3 : \uc5f4\ub78c\uad8c\ud55c \uccb4\ud06c.\ube44\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, \uc774\uacf3\uc5d0 \uc18d\ud558\uba74 \uc5f4\ub78c \uac00\ub2a5.\uc18d\ud558\uc9c0 \uc54a\uc73c\uba74, 2\ubc88, 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.\ubd80\ubd84\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, \uc774\uacf3\uc5d0 \uc18d\ud558\uba74 \uc5f4\ub78c \uac00\ub2a5.\uc18d\ud558\uc9c0 \uc54a\uc73c\uba74, 2\ubc88, 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.\uacf5\uac1c \ubb38\uc11c\uc778 \uacbd\uc6b0, 2\ubc88 3\ubc88\uc744 \ucd94\uac00\ub85c \uccb4\ud06c\ud568.
config.UserInfo_ApprovalG_VIEW = YYY

########################################################

####################### \uc0ad\uc81c  #####################

config.Use_ezDMS = NO
config.Use_MobileMgmt = NO
config.USE_OCS = NO
config.Use_ezKMS = NO
#SSL \uc0ac\uc6a9\uc5ec\ubd80 \uc124\uc815
config.ezInfoSSL = 

#L4 \uad00\ub828 config
config.curServer = SysServer1
#config.otherServer = SysServer2, SysServer3

#\uc804\uccb4 \uc11c\ubc84 \ubaa9\ub85d
#config.SysServer1 = http://jgw.kaoni.com
#config.SysServer1 = http://jmail.kaoni.com
#config.SysServer2 = http://jgw.kaoni.com
#config.SysServer4 = http://192.168.56.1:8888


#\ubb38\uc11c\uc720\ud1b5 ldap \uc811\uc18d \uc815\ubcf4
R_LServer = ldap://cen.dir.go.kr:389
R_LBaseDN = o=Government of Korea,c=KR


################ AD(Active Directory) \uc0ac\uc6a9 \uad00\ub828 ###################
#AD \uc0ac\uc6a9\uc5ec\ubd80 \ud14c\uc2a4\ud2b8 \uc815\ubcf4\uc774\uae30\uc5d0 \uace0\uac1d\uc0ac\uc5d0 \ub098\uac08\ub54c \ubcc0\uacbd\ud574\uc57c\ud568
#config.Common_Name1 = domain_name1
#config.Common_Name2 = domain_name2
#config.Company_Name = company_name
#config.Domain_Name = domain_name1.domain_name2
config.Common_Name1 = syl2017
config.Common_Name2 = dev
config.Company_Name = jongcomp
config.Domain_Name = syl2017.dev
#\uc811\uc18d URL
#config.PROVIDER_URL = ipaddress
config.PROVIDER_URL = 10.0.100.185
#\uc811\uc18d \ub3c4\uba54\uc778
#config.SECURITY_PRINCIPAL = account@domain_name1.domain_name2
config.SECURITY_PRINCIPAL = administrator@syl2017.dev
#\uc811\uc18d \ud328\uc2a4\uc6cc\ub4dc
#config.SECURITY_CREDENTIALS = password
config.SECURITY_CREDENTIALS = P@ssw0rd

############ \ud3fc\ube4c\ub354 config ############
config.reformServerURL = http://127.0.0.1:8088

#################### rest api \uad00\ub828 config ####################
config.attitudeGwServerURL = http://127.0.0.1:8080
config.journalGWServerURL = http://127.0.0.1:8080
config.ladderGwServerURL = http://127.0.0.1:8080
config.scheduleGwServerURL = http://127.0.0.1:8080
config.notificationGWServerURL = http://127.0.0.1:8080
################ \ud504\ub85c\uc81d\ud2b8 \uad00\ub9ac \uad00\ub828 ###################
config.projectGWServerURL = http://127.0.0.1:8080
############  \uc6f9\ud3f4\ub354 config ############ 
config.webFolderGwServerURL = http://127.0.0.1:8080
############  \uce90\ube44\ub2db config ############ 
config.cabinetGwServerURL = http://127.0.0.1:8080
config.cabinetPrimary = ko
config.cabinetSecondary = en
################ \uba54\ubaa8 \uad00\ub828 ###################
config.memoGwServerURL = http://127.0.0.1:8080
config.surveyGwServerURL = http://127.0.0.1:8080

############  \ud3ec\ud0c8 \uac1c\uc778\ud654 config ############ 
config.portalGwServerURL = http://127.0.0.1:8080
############ \uc778\ud130\ub137 \uc0ac\uc6a9 \uc5ec\ubd80 #############
config.useInternet = YES

#\uc624\ud53c\uc2a4 \uacb0\uc7ac \ubcc0\ud658 \uc11c\ubc84 IP
config.officeConverterServerURL = http://222.106.242.180:8080
config.officeTempUploadPath = /home/jmocha/officeTemp

############  \ud1b5\ud569\uac80\uc0c9 \uad00\ub828 \uc124\uce58\ub41c \uc11c\ubc84\ub85c \ubcc0\uacbd\ud574\uc57c\ud568 
############  ex) 10.0.171.21\uc758 \uacbd\uc6b0 \uc790\uccb4 \uc124\uce58 \ub418\uc5b4\uc788\uae30 \ub54c\ubb38\uc5d0 127.0.0.1\ub85c \ubcc0\uacbd 
config.totalSearchURL = http://127.0.0.1:6501/search/search.jsp

# RestTemplate \ucee4\ub125\uc158 \ud480 \ud0c0\uc784\uc544\uc6c3 \uc124\uc815
config.restConnectTimeout = 5000
config.restSocketTimeout = 30000

#################################### google \uad00\ub828 config ###################################
config.clientId = 848434482038-3e5tsi6elb7fd90gfiagf49gbl61mlie.apps.googleusercontent.com
config.clientSecret = W6Iapa-aBdkEUAE2_1MYCEpS
config.redirectURI = http://localhost:8080/ezSchedule/returnFromCallBack.do

#\ubcf4\uc548\uba54\uc77c \uc554\ud638 klib\uc0ac\uc6a9 \uc720\ubb34
config.useKlibEncrypt = NO

config.useMobileMail2 = N
#\uc5f0\ub3d9\ud638\ucd9c URL
config.connURL = http://127.0.0.1:8080

############ \uac8c\uc2dc\ud310 > \ube44\ud68c\uc6d0 \uc77d\uae30\uad8c\ud55c ############
config.guestDefaultTenantId = 0

config.tigris.acsUrl = /user/login/samlAuth.do
config.tigris.spEntityId = https://www.ezekp365g.com
config.tigris.idpUrl = https://test40.tigrison.com/sso/saml/login