
Globals.DbType = mysql
Globals.DriverClassName=org.mariadb.jdbc.Driver
Globals.Url=jdbc:mariadb://jrelg.kaoni.com:3307/jmocha?useSSL=false
Globals.UserName= ENC(HrbKM/rtW9ZM9db2/YNn68ED/oDNK2yu)
Globals.Password= ENC(9eGuLSXDWV5UbWHMG0JPahWBJi0BS9Uy)
Globals.language = ko
Globals.jndi =
Globals.jndiName =
