
Globals.DbType = mysql
Globals.DriverClassName=org.mariadb.jdbc.Driver
Globals.Url=jdbc:mariadb://10.0.100.175:3307/jmocha?useSSL=false
Globals.UserName= ENC(HrbKM/rtW9ZM9db2/YNn68ED/oDNK2yu)
Globals.Password= ENC(GXjSiyHa4Xp68UVjFV2DXprKmjbsCBuF)
Globals.language = ko
Globals.jndi =
Globals.jndiName =
